edmcouncil/fibo

etc/fibo-vue/package-lock.json, etc/fibo-vue/package.json, etc/fibo-vue/src/views/FIBOReleaseNotes.vue, etc/fibo-vue/yarn.lock
The FIBO release notes webpage needs a top button.
Fixes: # https://github.com/edmcouncil/fibo/issues/815
- [ x] I'm familiar with the [FIBO developer quide](../CONTRIBUTING.md#contributing-to-the-fibo-code). My contribution meets all the requirements described there.
- [x ] My contribution follows the [principles of best practices for FIBO](../ONTOLOGY_GUIDE.md).
=> Top button for the FIBO release notes webpage

BE/LegalEntities/LegalPersons.rdf
revised definition of legal person per suggestion from the user community
Fixes: #274, [BE-206](https://jira.edmcouncil.org/browse/BE-206) (JIRA)
=> BE-206 #comment - issue #274

BP/SecuritiesIssuance/DebtIssuance.rdf
Corrected URI for debt issuance
Fixes: #843, #845
=> FND-843 #comment - correct URI in DebtIssuance

MD/EquityTemporal/EquityPricing.rdf
Corrected URI issue in equity pricing
Fixes: #850
=> MD-850 #comment - corrected URI in equity pricing

.github/pull_request_template.md
Signed-off-by: Robert Trypuz <robert.trypuz@makolab.com>
Changes in the FIBO's Pull Request template.
Fixes: #836
=> Changes in the FIBO's Pull Request template

etc/fibo-vue/src/components/ModuleTree.vue, etc/fibo-vue/src/views/Ontology.vue
Commit: 86c4c88969a4cb159f9032ec6af42b2254461d91 [86c4c88]
Parents: 4ace24859f
Author: kbalcerek <kbalcerek@o2.pl>
Date: wtorek, 18 lutego 2020 13:53:55
Committer: kbalcerek
Signed-off-by: kbalcerek <kbalcerek@o2.pl>
Commiting once again changes done in Commit: 86c4c88969a4cb159f9032ec6af42b2254461d91 because they were overwritten by mistake
Fixes: #824
=> Commiting once again changes done in

etc/fibo-vue/.eslintrc.js, etc/fibo-vue/package.json, etc/fibo-vue/src/views/Ontology.vue, etc/fibo-vue/vue.config.js, etc/fibo-vue/yarn.lock
Divide FIBO search results into pages
Fixes: #901
=> Divide FIBO search results into pages

BE/LegalEntities/FormalBusinessOrganizations.rdf, BE/LegalEntities/LEIEntities.rdf, DER/DerivativesContracts/SwapsIndividuals.rdf, FBC/FinancialInstruments/FinancialInstruments.rdf, FBC/FunctionalEntities/BusinessRegistries.rdf, FBC/FunctionalEntities/EuropeanEntities/EURegulatoryAgencies.rdf, FBC/FunctionalEntities/EuropeanEntities/EuropeanFinancialServicesEntitiesIndividuals.rdf, FBC/FunctionalEntities/InternationalRegistriesAndAuthorities.rdf, FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USMarketsAndExchangesIndividuals.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf, IND/InterestRates/MarketDataProviders.rdf, IND/MarketIndices/EquityIndexExampleIndividuals.rdf, LOAN/Loans/LoanBasicTerms.rdf
This resolution eliminates both the Registered and Registration address classes as part of our overall address rationalization effort, also hasPrimaryAddress property, which was misleading.  It replaces RegisteredAddress with ConventionalStreetAddress and RegistrationAddress with PhysicalAddress (since a registration address can, in some cases, be a post office address).  Also, to improve the address-related property hierarchy and usability, it moves hasHeadquartersAddress from FBC to BE.
Fixes: #928 / FBC-241
=> FBC-241 #comment - Rationalize/Eliminate Registered and Registration addresses

FND/Utilities/Analytics.rdf
Corrected typing on a data range union for qualified measure.
Fixes: #933 /FND-292
=> FND-292 #comment - Unexpected triple in 'qualified measure'

FBC/FunctionalEntities/EuropeanEntities/EuropeanFinancialServicesEntitiesIndividuals.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
This resolution fixes a handful of orphans that were left over from the LCC property revision, somehow missed in that process.
Fixes: #940 /FBC-244
=> FBC-244 #comment - addressed orphaned properties

SEC/Securities/SecuritiesIdentificationIndividuals.rdf
Corrected punning in the definition of financial s……ervice provider definitions that register and issue certain identifiers
Fixes: #939 / SEC-121
=> SEC-121 #comment - Inconsistent usage of 'registers' and 'issues'

SEC/Equities/EquitiesExampleIndividuals.rdf, SEC/Equities/EquityInstruments.rdf
Added the concept of an equity issuer; moved the domain of several properties from share to equity issuer and included appropriate restrictions (optional) on equity issuer for those properties; updated equities example individuals accordingly.
Fixes: #870  / SEC-122
=> SEC-122 #comment - Property hasSharesOutstanding should be applied to the Entity

IND/MarketIndices/EquityIndexExampleIndividuals.rdf, SEC/Securities/Baskets.rdf
Replaced property hasIdentity with involves to ind……icate securities that are referenced by basket constituents
Fixes: #872 / SEC-123
=> SEC-123 #comment - hasIdentity is not the correct property to use to link a basketConstituent to its security

FND/Utilities/Analytics.rdf, IND/EconomicIndicators/EconomicIndicators.rdf
Revised the definition of numeric index to be numeric index value per discussion in the IND FCT; updated its use in economic indicators accordingly
Fixes: #835 / FND-298
=> FND-298 - Several changes are needed to the definition of numeric index

BE/OwnershipAndControl/ControlParties.rdf, BE/OwnershipAndControl/OwnershipParties.rdf, FND/OwnershipAndControl/Control.rdf, FND/OwnershipAndControl/Ownership.rdf, FND/Parties/Parties.rdf
Adds the concept of a situation, actor, and undergoer to the FND Parties ontology, including many of the lattice relations between them, sufficient to fully represent the concepts of Ownership and Control as situations in FND, and to extend them to support entity ownership in BE, while retaining the original properties related to entity ownership, but augmenting them with additional semantics to enable full relationship reasoning to function properly.
Note that this does not add -all- lattice relations possible, nor does it complete the control connections or reconcile other ownership relations in BE, which will be done under other issue resolutions.  However, reasoning results are fully compatible with the original set of relationships …
=> BE-44 - There are a number of gaps related to ownership and control that require representation of the concept of a situation

FND/Places/NorthAmerica/USPostalServiceAddresses.rdf
Simplified reasoning structure for OverseasMilitar……yAddress, replaced max 1 restriction on Puerto Rico address with min 0 to improve reasoning results
Fixes: #1060 / FND-303
=> FND-303 - Reasoning issues in the USPostalServicesAddressing ontology

BE/OwnershipAndControl/Executives.rdf
Fixed the label (likely due to a copy/paste error).
Fixes: #1088 / BE-222
=> BE-222 - Correct label on hasAuthorizedParty

FBC/ProductsAndServices/FinancialProductsAndServices.rdf
Fixed the label and revised the definition to be more descriptive of what the stage 'terminated trade' means
Fixes: #1100
=> FBC-256 - Correct label on terminated trade

IND/EconomicIndicators/EconomicIndicators.rdf
Added a number of definitions for aspects of the unemployed/underemployed population that are relevant to statistics related to COVID-19 and eliminated circularities in property definitions
Fixes: #1106 / IND-97
=> IND-97  - Need to add definitions for marginally attached and discouraged workers

BE/GovernmentEntities/EuropeanJurisdiction/UKGovernmentEntitiesAndJurisdictions.rdf, BE/GovernmentEntities/GovernmentEntities.rdf
Added the concept of a devolved government as well as entities for the devolved governments in the UK for Scotland, Wales, and Northern Ireland
Fixes: #1120 / BE-205
=> BE-205 - Create classes for devolved administrations in the United Kingdom

FBC/FunctionalEntities/BusinessCenters.rdf, LOAN/LoanContracts/LoanHMDA.rdf
Eliminate circular imports in FBC Business Centers and LOAN HMDA, and revise definitions in Business Centers to eliminate circularity and make them ISO 704 compliant
Fixes: #1152 / FBC-259, LOAN-158
=> FBC-259 and LOAN-158 - Eliminate circular owl:imports

AboutFIBOProd.rdf, FBC/AllFBC.rdf, FBC/DebtAndEquities/CreditEvents.rdf, FND/Agreements/Contracts.rdf
This resolution addresses issues raised against the credit events ontology, including the need to fix inheritance, generalize aspects of the ontology, improve definitions, and complete integration with other parts of FIBO in order to release it.
Fixes: #1155 / FBC-236
=> FBC-236 - Issues with credit events

LOAN/AllLOAN.rdf
Corrected import for IND ontologies needed for Debt Instruments to load properly
Fixes: #1154  / LOAN-159
=> LOAN-159 - Mistyped import in AllLOAN ontology

DER/DerivativesContracts/DerivativesMasterAgreements.rdf
corrected prefix in the master agreements ontology for fibo-fnd-arr-doc
Fixes: #1161 / DER-76
=> DER-76 - Bad prefix definition

FND/Arrangements/IdentifiersAndIndices.rdf
#comment - this change to create a reassignable identifier wa……s overwritten for some reason and need to be reinstated
This change to create a reassignable identifier wa……s overwritten for some reason and need to be reinstated
Fixes: #1139 / FND-316
=> FND-316 - Need to add the concept of a reassignable identifier that is time constrained

BE/FunctionalEntities/FunctionalEntities.rdf
Refined definitions to address feedback on FBC-260 with respect to merchants and merchant codes, clarifying definitions, adding notes, and eliminating a redundant property
Fixes: #1175 / BE-226
=> BE-226 - Additional refinement is needed regarding merchants and merchant category codes

AboutFIBODev.rdf, AboutFIBOProd.rdf, BE/AllBE-ExampleIndividuals.rdf, BE/AllBE-ReferenceIndividuals.rdf, BE/GovernmentEntities/LatinAmericanJurisdiction/CentralAmericanGovernmentEntitiesAndJurisdictions.rdf, BE/GovernmentEntities/LatinAmericanJurisdiction/SouthAmericanGovernmentEntitiesAndJurisdictions.rdf, BE/GovernmentEntities/MetadataBEGovernmentEntities.rdf, catalog-v001.xml
This issue resolution incorporates government entities, governments, and jurisdictions for Central and South America for all independent entities identified in the U.N. M49 codes.  These and entities for other parts of the world are increasingly important for ongoing AML and KYC initiatives.
Fixes: #1206 / BE-224
=> BE-224 - Additional government entities and jurisdictions are needed for bank initiatives and to support retail FIBO users

SEC/Equities/EquityCFIClassificationIndividuals.rdf, SEC/Equities/EquityInstruments.rdf
Updated approach to representing voting rights to create an exhaustive set of classes/nominals representing the various options, revised the CFI individuals accordingly and updated some definitions to eliminate additional ambiguity
Fixes: #1226 / SEC-73
=> SEC-73 - Revise the way that voting rights are represented for equities

SEC/Funds/Funds.rdf, SEC/Funds/MetadataSECFunds.rdf
Corrected domain on isOpenEnded to be PooledFund; also added metadata file for Funds
Fixes: #1242
=> Domain on property isOpenEnded is incorrect and a metadata file is missing

BE/OwnershipAndControl/ControlParties.rdf, BE/OwnershipAndControl/CorporateControl.rdf, FND/OwnershipAndControl/Control.rdf
Simplified control concepts and relations, completed top-level control patterns, integrated control parties with the more complete lattice pattern, and eliminated ambiguity in some definitions.
Fixes: #1246 / BE-228
=> BE-228 - Simplify the control hierarchy in FND/BE and rationalize control relationships

DER/DerivativesContracts/Swaps.rdf, DER/RateDerivatives/IRSwaps.rdf
Added basic fixed and floating legs as higher level concepts common to many swaps, eliminated ambiguity in definitions, and revised editorial note annotations to be explanatory notes as appropriate
Fixes: #1249 / DER-86
=> DER-86 - Create common fixed leg and floating leg concepts in the swaps ontology

AboutFIBOProd.rdf, SEC/AllSEC-ExampleIndividuals.rdf, SEC/AllSEC-ReferenceIndividuals.rdf, SEC/AllSEC.rdf, SEC/Funds/Funds.rdf, SEC/Funds/MetadataSECFunds.rdf
This resolution revises metadata and load files to integrate the Funds ontology into production / release.
Fixes: #1254
=> SEC-1254 - Release the core Funds ontology

BE/OwnershipAndControl/CorporateOwnership.rdf
Augmented the definition of beneficial owner to incorporate the situation (allowing representation of ownership percentage and time frame) as well as properties connection the owner to the thing they control in that situation
Fixes: #1262 / BE-230
=> BE-230 - The representation of beneficial owner is incomplete

BE/LegalEntities/NorthAmericanEntities/USExampleEntities.rdf, DER/DerivativesContracts/SwapsIndividuals.rdf, FBC/FunctionalEntities/EuropeanEntities/EURegulatoryAgencies.rdf, FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf, IND/InterestRates/MarketDataProviders.rdf
Revised the LEI URIs in reference and example ontologies to the new form published by the GLEIF on data.world and updated related data
Fixes: #1278 / FBC-268
=> FBC-268 - Revise LEI URIs in examples to reflect the latest updates from GLEIF

BE/FunctionalEntities/FunctionalEntities.rdf, BE/LegalEntities/LEIEntities.rdf
Cleaned up circular definitions identified through hygiene testing in LEI Entities and Functional Entities in BE
Fixes: #1349 / BE-234
=> BE-234 - Eliminate remaining circular definitions in BE

BE/LegalEntities/CorporateBodies.rdf, BE/LegalEntities/FormalBusinessOrganizations.rdf, BE/SoleProprietorships/SoleProprietorships.rdf
Eliminated unnecessary references to external resources, including some that had wrong datatypes, and cleaned up a few definitions in corporate bodies in particular (where the errors were found)
Fixes: #1414 / BE-235
=> BE-235 - Eliminate unnecessary references to external sources, including one with an incorrect datatype in Business Entities (BE)

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf, FBC/FunctionalEntities/MarketsIndividuals.rdf
Update the business centers and markets reference data to reflect the latest updates to the ISO 10383 MIC codes
Fixes: #1436 / FBC-278
=> FBC-278 - Update the MIC codes per the latest version published by ISO (ISO 10383)

CONTRIBUTING.md, README.md
Signed-off-by: Robert Trypuz <robert.trypuz@makolab.com>
Updated files:
- CONTRIBUTING.md
- README.md
=> minor changes to the documentation

BE/LegalEntities/CorporateBodies.rdf
Eliminate see also reference that results in a 404 error, i.e., the document is no longer available
Fixes: #1469 / BE-210
=> BE-210 - SeeAlso link on BenefitCorporation does not resolve

BE/OwnershipAndControl/ControlParties.rdf, BE/OwnershipAndControl/CorporateControl.rdf, BE/OwnershipAndControl/CorporateOwnership.rdf, BE/OwnershipAndControl/Executives.rdf, FND/OwnershipAndControl/Control.rdf
This resolution aligns the concept of control and related properties with the situational pattern, using a parallel structure to that of ownership.  It adds several properties, migrated some restrictions that had party to role relationships to those that reflect the pattern, and aligned the independent party to independent party or thing relations (i.e. controls, and isControlledBy) with the pattern to eliminate confusion and for ease of downstream use. 
Fixes: #1498 / FND-344
=> FND-344 - Better integrate control relations with the situation pattern

BE/LegalEntities/LEIEntities.rdf, FND/AgentsAndPeople/Agents.rdf, FND/AgentsAndPeople/People.rdf, FND/Organizations/Organizations.rdf, FND/Parties/Parties.rdf, FND/Relations/Relations.rdf
This resolution introduces a new custom datatype, Text, which represents the union of xsd:string and rdf:langString, allowing better representation of names and descriptions that may be expressed in various languages.  It also adds the concept of a structured name, and augments parties, people, and organizations to use it, as a current approach to handling name patterns rather than less expressive string values, as appropriate.
Fixes: #1533 / FND-346 / FND-245 / FND-74
=> FND-346  - Need the definition of a structured name and definition of a new datatype for the combination of xsd:string and rdf:langString

FBC/FinancialInstruments/InstrumentPricing.rdf
Revised the explanatory note on hasLotSize and added examples to clarify usage
Fixes: #1546 / DER-100
=> DER-100 - The explanatory note on hasLotSize needs to be revised

LOAN/AllLOAN.rdf, LOAN/LoanContracts/LoanEvents.rdf
This resolution addresses issues in the LoanEvents ontology, including the following: (1) Corrected punning issues in LoanEvents due to incorrect property inheritance, (2) cleaned up other redundant properties and property names, (3) improved integration with other parts of FIBO, and (4) added the LoanEvents ontology to AllLOAN for ease of testing.  Note that additional work is required in order to make this releasable, including but not limited to moving some classes to where they belong in FND, better integration with lifecycle phases and activities related to loan processing, and the like.
Fixes: #1566
=> LOAN-1566 - Inconsistent typing of hasJudgementAmount

IND/EconomicIndicators/EconomicIndicators.rdf
=> Removal of rdf:disjointWith

catalog-v001.xml
corrected the high-level catalog to eliminate references ……to nonexistent files
Corrected the high-level catalog to eliminate references to nonexistent files
Fixes: #1636
=> FIBO-1636 - Update for catalog-v001.xml

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf, FBC/FunctionalEntities/MarketsIndividuals.rdf
Revised the reference data set for the ISO 10383 Codes for exchanges and market identification (MIC) codes as of 12/14/2021, including an additional municipality which was added to the business center individuals
Fixes: #1656 / FBC-292
=> FBC-292 - Generate the latest ISO MIC codes for Q4 2021

FND/Arrangements/Documents.rdf
Clarify the definition of legal document and augment the definition with explanatory notes and examples
Fixes: #1663 / FND-350
=> FND-350 - The definition of 'legal document' needs cleaning up and additional explanation

README.md
Revise the readme file to correspond to the text provided to use for the overall EDM Council FIBO web site
Fixes: #1688
=> Update readme file to more accurately represent what FIBO is

FND/Utilities/Analytics.rdf
Removed several unused imports to clean up the analytics ontology
Fixes: #1690
=> FND-359 - Eliminate unused imports in Analytics

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf, FBC/FunctionalEntities/MarketsIndividuals.rdf
Revised the MIC codes and corresponding business centers / municipalities per the latest ISO revisions
Fixes: #1760 / FBC-294
=> FBC-294 - Revise the ISO MIC codes to reflect the latest updates from ISO

DER/RateDerivatives/IRSwaps.rdf, DER/SecurityBasedDerivatives/EquitySwaps.rdf
Eliminated deprecated swap elements to clean things up
Fixes: #1777 / DER-128
=> DER-128 - Eliminate deprecated swaps elements in DER

etc/onto-viewer-web-app/config/application_config.yaml
Signed-off-by: Patrycja Miazek <patrycja.miazek@makolab.com>
=> Add new configuration file

BE/Corporations/Corporations.rdf, BE/FunctionalEntities/FunctionalEntities.rdf, BE/GovernmentEntities/AsianJurisdiction/EasternAsiaGovernmentEntitiesAndJurisdictions.rdf, BE/GovernmentEntities/EuropeanJurisdiction/EUGovernmentEntitiesAndJurisdictions.rdf, BE/GovernmentEntities/EuropeanJurisdiction/EasternEuropeGovernmentEntitiesAndJurisdictions.rdf, BE/GovernmentEntities/GovernmentEntities.rdf, BE/GovernmentEntities/NorthAmericanJurisdiction/USGovernmentEntitiesAndJurisdictions.rdf, BE/LegalEntities/CorporateBodies.rdf, BE/LegalEntities/FormalBusinessOrganizations.rdf, BE/LegalEntities/LEIEntities.rdf, BE/LegalEntities/LegalPersons.rdf, BE/LegalEntities/NorthAmericanEntities/USExampleEntities.rdf, BE/OwnershipAndControl/CorporateControl.rdf, BE/OwnershipAndControl/Executives.rdf, BE/OwnershipAndControl/MetadataBEOwnershipAndControl.rdf, BE/OwnershipAndControl/OwnershipParties.rdf, BE/Partnerships/Partnerships.rdf
The changes made in this resolution are purely editorial, addressing text formatting issues from hygiene testing and dead links in the BE ontologies
Fixes: #1797 / #1803 / BE-248
=> BE-248 - Eliminate text formatting issues and dead links

IND/AllIND-ExampleIndividuals.rdf, IND/AllIND-NorthAmerica.rdf, IND/AllIND-ReferenceRates.rdf, IND/AllIND.rdf, IND/EconomicIndicators/EconomicIndicators.rdf, IND/EconomicIndicators/NorthAmericanIndicators/CAEconomicIndicators.rdf, IND/EconomicIndicators/NorthAmericanIndicators/USEconomicIndicators.rdf, IND/MarketIndices/BasketIndices.rdf, IND/MetadataIND.rdf
addressed text formatting hygiene issues and cleaned up dead links in IND, primarily in relation to economic indicators, where numerous government links had been moved
Fixes: #1797 / IND-122
=> IND-122 - Inactive hyperlinks in annotation properties

SEC/AllSEC-ExampleIndividuals.rdf, SEC/AllSEC-ReferenceIndividuals.rdf, SEC/AllSEC.rdf, SEC/Debt/Bonds.rdf, SEC/Debt/MortgageBackedSecurities.rdf, SEC/Equities/DepositaryReceipts.rdf, SEC/Equities/EquityCFIClassificationIndividuals.rdf, SEC/Equities/EquityInstruments.rdf, SEC/Funds/Funds.rdf, SEC/MetadataSEC.rdf, SEC/Securities/ParametricSchedules.rdf, SEC/Securities/SecuritiesIdentification.rdf, SEC/Securities/SecuritiesIdentificationIndividuals.rdf, SEC/Securities/SecuritiesIssuance.rdf, SEC/Securities/SecurityAssets.rdf
1. Addressed text formatting issues in SEC Debt, Equities, and Funds modules
2. Cleaned up links and addressed formatting issues in the SEC Securities modules
3. Cleaned up metadata files in SEC and added missing contributor
Fixes: #1814 / SEC-180
=> SEC-180 - Need to address hygiene issues in text formatting and clean up dead links in SEC

AboutFIBOProd-IncludingReferenceData.rdf, AboutFIBOProd-TBoxOnly.rdf, AboutFIBOProd.rdf, DER/AllDER.rdf, DER/DerivativesContracts/ExoticOptions.rdf
1. Clean up the declarations and other header content in preparation for release of exotic options
2. Integrate the Exotic Options ontology into the various load files, including about prod
Fixes: #1821 / DER-133
=> DER-133 - Release the exotic options ontology

etc/onto-viewer-web-app/config/ontology_config.yaml
Signed-off-by: Patrycja Miazek <patrycjamiazek17@gmail.com>
=> Update config file

AboutFIBOProd-IncludingReferenceData.rdf, AboutFIBOProd-TBoxOnly.rdf, AboutFIBOProd.rdf, FBC/AllFBC.rdf, FBC/FinancialInstruments/Settlement.rdf
Addressed remaining feedback on the Settlement ontology, adjusted a few definitions to be ISO 704 compliant, and changed its status to release for the Q3 2022 FIBO Release
Fixes: #1831 / FBC-185
=> FBC-185 - Several comments on the Settlement ontology

FBC/FunctionalEntities/MarketsIndividuals.rdf
Revised MIC codes as of September 2022 for the FIBO Q3 2022 release
Fixes: #1835 / FBC-302
=> FBC-302 - Revise the ISO MIC codes to reflect the latest updates from ISO

etc/onto-viewer-web-app/config/integration_config.yaml
Fixes: #1903 
Fixes: #ISSUE_NUMBER
=> integration.yaml added

BE/LegalEntities/LegalPersons.rdf, FBC/FunctionalEntities/FinancialServicesEntities.rdf
Add a French label for special purpose vehicle and synonym for institutional investor
Fixes: #1916 / FBC-310
=> FBC-310 - Augment two classes with labels in French for demonstration purposes

DER/DerivativesContracts/CommoditiesContracts.rdf, FBC/FinancialInstruments/FinancialInstruments.rdf
1. Augmented the definition of a commodity instrument to include the commodity, a quantity of that commodity, and its value as of the execution date of the contract
2. Revised the definition of commodity spot contract, commodity basket constituent, and commodity underlier accordingly
Fixes: #1925 / DER-84
=> DER-84 - Commodity swaps are missing the concept of how much and a price at some point in time

IND/InterestRates/CommonInterestRates.rdf
Updated the FpML reference interest rates per the latest revision as of 10 March 2023
Fixes: #1934 / IND-125
=> IND-125 - Revise FpML reference rates to reflect the latest revisions as of June 2023

SEC/Equities/EquityInstruments.rdf
Resolved inconsistency in the restriction on limited partnership unit as well as a minor hygiene issue
Fixes: #ISSUE_NUMBER
=> SEC-187 - Address reasoning issue with the definition of limited partnership unit in Equities

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
1. Initial update to the business centers individuals per latest generated FpML codes
2. Second pass to include the municipalities per the ISO 10383 MIC codes updated in March 2023
Fixes: #1939 / FBC-314
=> FBC-314 - Update the FpML Business Centers based on the latest (March 2023) revisions

BP/SecuritiesIssuance/PrivateLabelMBSIssuance.rdf, SEC/Debt/CollateralizedDebtObligations.rdf, SEC/Debt/MortgageBackedSecurities.rdf
Moved all tranche related concepts from MBS to CDOs, so that we can focus on basic MBS in the MBS ontology
Fixes: #1951 / SEC-188
=> SEC-188 - Tranche related concepts in MBS should be moved to CDOs

AboutFIBOProd-IncludingReferenceData.rdf, AboutFIBOProd-TBoxOnly.rdf, AboutFIBOProd.rdf, SEC/AllSEC.rdf, SEC/Debt/AssetBackedSecurities.rdf
Revised the ABS ontology for release
Fixes: #1968 / SEC-194
=> SEC-194 - Complete the work to release the ABS ontology

SEC/README.md
=> documentation correction 

BE/GovernmentEntities/AsianJurisdiction/WesternAsiaGovernmentEntitiesAndJurisdictions.rdf
Addressed spelling errors in the Western Asian government entities ontology
Fixes: #1955
=> GitHub-1955 - Spelling error "Sultinate" should be "Sultanate"

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
Revise the business center individuals and MIC codes to reflect the Q1 2024 update by ISO
Fixes: #2004 / FBC-319
=> FBC-319 - Revise the ISO MIC codes to reflect the latest updates from ISO

FND/DatesAndTimes/FinancialDates.rdf
Added the concept of a business calendar, which is needed for mapping to ACTUS
Fixes: #2006 / FBC-318
=> FBC-318 - Add the concept of a business calendar

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
Revised the FpML business centers and MIC codes with the latest revisions from ISO
Fixes: #2022 / FBC-320
=> FBC-320 - Revise the ISO MIC codes to reflect the latest updates from ISO

IND/MarketIndices/EquityIndexExampleIndividuals.rdf
Replaced properties from analytics with those from Commons quantities and units, due to migration/deprecation
Fixes: #2051
=> GitHub-2051 - Eliminate remaining issues related to deprecated elements that are still used somewhere in FIBO

DER/DerivativesContracts/Swaps.rdf, FBC/FinancialInstruments/FinancialInstruments.rdf
Cleaned up the definitions of and added notes on swap and swap leg, per the issue; also eliminated a long-time deprecated element
Fixes: #2059 / DER-113
=> DER-113 - Need to connect properties of a swap to the legs that may "inherit" those properties

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
Revised the market identification codes (MIC codes) and related business centers per the latest revisions to the ISO codes (Q4 2024)
Fixes: #2082 / FBC-323
- [x} Hygiene tests have been applied by a PR with "(WIP)" in title.
=> FBC-323 - Revise the ISO MIC codes to reflect the latest updates from ISO (Q4 2024) 

IND/InterestRates/CommonInterestRates.rdf
Revised the FpML rates controlled vocabulary to cover the most recent updates
Fixes: #2084 / IND-127
=> IND-127 - Revise the FpML rates controlled vocabulary to reflect Q4 2024 revisions

FBC/FunctionalEntities/FinancialServicesEntities.rdf
Corrected spelling error in label
Fixes: #2091
=> Typo in the label of DataProcessingServicer

DER/DerivativesContracts/DerivativesBasics.rdf
Added details about the registry and registry entry for the UPI
Fixes: #2099 / DER-146
=> DER-146a - Augment the definition for the ISO 4914 Unique Product Identifier for OTC instruments with additional annotations and examples

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
Revised MIC codes per the Q1 2025 release
Fixes: #2117 / FBC-326
=> FBC-326 - Revise the ISO MIC codes to reflect updates made in Q1 2025

AboutFIBOProd-IncludingReferenceData.rdf, AboutFIBOProd-TBoxOnly.rdf, AboutFIBOProd.rdf, DER/AllDER.rdf, DER/DerivativesContracts/DerivativesMasterAgreements.rdf, DER/DerivativesContracts/MetadataDERDerivativesContracts.rdf, FND/Agreements/Contracts.rdf
Completed final modifications to the derivative master agreements ontology and changed its status to 'release'.
Fixes: #2130 / DER-55
=> DER-55b - Potential issues with the DerivativesMasterAgreements ontology

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf, FBC/FunctionalEntities/NorthAmericanEntities/USMarketsAndExchangesIndividuals.rdf
1. Revised business centers to include those that were added in Q2
2. Updated ISO MIC codes were included
3. Revised references to service providers in markets examples to the latest LEI-based references in the updated MIC codes
Fixes: #2136 / FBC-335
=> FBC-335 - Revise the ISO MIC codes to reflect the latest updates from ISO

AboutFIBOProd-IncludingReferenceData.rdf, AboutFIBOProd-TBoxOnly.rdf, AboutFIBOProd.rdf, LOAN/LoansSpecific/GreenLoans.rdf
Update metadata to release this additional ontology.
Fixes: #2138
=> GitHub-2138 - Release the GreenLoans ontology for inclusion in the Q2 2025 FIBO Release

SEC/AllSEC-ExampleIndividuals.rdf
Corrected IRI in load file and revised metadata
Fixes: #2140
=> GitHub-2140 - Broken import in example ontology on FIBO master branch

FBC/DebtAndEquities/Debt.rdf
Corrected typo (missing word) in the definition
Fixes: #2154
=> GitHub-2154 - Problem with HAS ANTICIPATED NUMBER OF PAYMENTS

DER/DerivativesContracts/RightsAndWarrants.rdf
Added exotic warrant to the rights and warrants ontology
Fixes: #2158 / DER-153
=> DER-153 - Missing the concept of an exotic warrant

FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
Revised the Business Centers and MIC codes to reflect the latest updates from ISO
Fixes: #2169 / FBC-337
=> FBC-337 - Revise the ISO MIC codes to reflect the latest updates from ISO
