- README.md
Signed-off-by: trypuz <robert.trypuz@makolab.com>
E-mail address change in the README file
- slackinvite@edmcouncil.org -- > fibo@edmcouncil.org
Fixes: #852
> slackinvite@edmcouncil.org -- > fibo@edmcouncil.org

- etc/process/Jenkinsfile
Signed-off-by: Robert Trypuz <robert.trypuz@makolab.com>
FIBOPedia is deprecated. Data dictionary is now served in one file (Excel or CSV).
Fixes: https://github.com/edmcouncil/ontology-publisher/issues/13
> datadictionary and fibopedia removed from the Jenkins pipeline

- BE/LegalEntities/CorporateBodies.rdf
- FND/Organizations/FormalOrganizations.rdf
This issue addresses #866 by loosening constraints on the [isDomiciledIn](https://spec.edmcouncil.org/fibo/ontology/FND/Organizations/FormalOrganizations/isDomiciledIn) property in FND FormalOrganizations, adding a restriction on a formal organization to say that it is domiciled in at least one geopolitical entity, and revising definitions in that ontology to be ISO 704 compliant;  eliminating a constraint on corporation which was more restrictive and was made redundant by this change. 
Fixes: #866 / FND-279
> FND-279 #comment - Loosened constraints on the isDomiciledIn property

- AboutFIBODev.rdf
- AboutFIBOProd.rdf
- BE/AllBE-NorthAmerica.rdf
- FND/AllFND-NorthAmerica.rdf
- FND/Places/Addresses.rdf
- FND/Places/MetadataFNDPlaces.rdf
- FND/Places/NorthAmerica/USPostalServiceAddresses.rdf
- FND/Places/NorthAmerica/USPostalServiceAddressesIndividuals.rdf
- FND/Utilities/AnnotationVocabulary.rdf
- catalog-v001.xml
These extensions are needed for LOAN, where for some use cases it is important to know whether or not an address is a military address. Privacy restrictions on customer data in the US require that military addresses are treated with additional care, for example, and members of the service that are stationed overseas are given consideration with respect to delinquency. The extensions include a number of unconventional addresses, in addition to US military addresses, such as rural route addresses, highway contract addresses, private mailboxes, and general delivery addresses.
Fixes: #921 / FND-290 and FBC-226
> FND-290 - Need to extend addresses to include the specifics for US addresses per the USPS Pub 28 standard

- FND/AgentsAndPeople/People.rdf
This resolution revises a restriction on the verifiesAddress property on identity document to be a qualified cardinality restriction rather than unqualified (bug fix).
Fixes: #930 / FND-291
> FND-291 #comment - corrects invalid cardinality restriction on identity document

- FBC/FunctionalEntities/Markets.rdf
This resolution corrects the typing on the property 'operates in municipality' and makes it a subproperty of hasMunicipality.
Fixes: #931 / FBC-243
> FBC-243 Property 'operates in municipality' defined as a data property and used as object property

- SEC/Debt/DebtInstruments.rdf
removed erroneous subproperty relationship on hasEstateOrDeathPutFeature
Fixes: #932 / SEC-120
> SEC-120 #comment - 'has estate or death put feature' inconsistent property definitions

- FBC/FunctionalEntities/RegistrationAuthorities.rdf
This resolution fixes the misspelling, likely overlooked for a long time.
Fixes: #944  / FBC-246
> FBC-246  - Misspelled annotation in RegistrationAuthorities

- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Securities/SecuritiesListings.rdf
Eliminated the redundant hasIssue property and revised the definition of 'lists' to reflect its semantics better.
Fixes: #871 / SEC-116
> SEC-116 - Properties lists and hasIssue seem redundant for class Listing

- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
Removed redundant institution type class, which was flagged by pellet lint as having a very large number of disjuncts and is not needed to answer the question, 'what kind of institution is this organization?'
Fixes: #946 /FBC-247
> FBC-247 #comment - The definition of InstitutionType with respect to the NIC repository creates a disjunction of 19 elements which is not recommended

- FND/Places/Addresses.rdf
- FND/Places/NorthAmerica/USPostalServiceAddressesIndividuals.rdf
Added property hasLocaleDesignation to Addresses; added the locale designation to US state and territory codes as well as to Canadian province codes, which are specified in USPS Pub  28, although created and managed by the Canadian government in Ottawa.
Fixes: #947 / FND-294
> FND-294 #comment - An additional datatype property is needed for local designations for states and provinces

- AboutFIBODev.rdf
- AboutFIBOProd.rdf
Revised top-level, github versions of the FIBO about files to provide proper header metadata, a proper IRI for each, and organize the ontologies so that they are grouped by domain area for ease of use by FIBO developers/github users.
Fixes: #814  / FND-295
> FND_295 - The AboutFIBOProd and AboutFIBODev ontologies have bogus IRIs and need to be documented with metadata that can help github users

- FND/Places/Addresses.rdf
Removed an empty skos:definition annotation from physical address identifier
Fixes: #970 / FND-296
> FND-296 - Extra blank skos:definition on fibo-fnd-plc-adr:PhysicalAddressIdentifier

- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
Signed-off-by: Elisa Kendall ekendall@thematix.com
Corrected misspelled URI prefix in US Regulatory Agencies
Fixes: #971 / FBC-252
> FBC-252 - URI error in individuals (caught by Pellet Lint)

- LOAN/LoanContracts/LoanCore.rdf
This resolution corrects an incorrect annotation prefix in LoanCore for skos:scopeNote.
Fixes: #984 / LOAN-150
> LOAN-150 - The LoanCore ontology includes a bad annotation prefix

- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
Corrected wrong datatype on annotation properties in US Regulatory Agencies
Fixes: #979  / FBC-253
> FBC-253 - "RSSD ID" wrong datatype

- DER/AssetDerivatives/AssetDerivatives.rdf
- DER/AssetDerivatives/EquityForwards.rdf
- DER/CommoditiesDerivatives/CommodityForwards.rdf
- DER/DerivativesContracts/Forwards.rdf
- DER/DerivativesContracts/OptionContractsOnFutures.rdf
- DER/DerivativesContracts/Options.rdf
- DER/ExchangeTradedDerivatives/ExchangeTradedOptions.rdf
- DER/ExchangeTradedDerivatives/Futures.rdf
- DER/FxDerivatives/FxForwards.rdf
- DER/FxDerivatives/FxOptions.rdf
This resolution eliminates the bad reference to the MD property that was likely deleted in a prior clean-up pass, eliminates references that use long URIs rather than abbreviated IRIs in Futures (which caused this reference to be missed), ExchangeTradedOptions and OptionContractOnFuture, and eliminates a significant amount of technical debt (redundancy, indirection, etc.) in the Futures and OptionContractOnFuture ontology.  Note that the latter should be merged with another derivatives ontology in a follow-up pass.
Fixes: #989 / DER-68
> DER-68 - Orphaned property and considerable duplication in the Futures ontology

- BP/MetadataBP.rdf
- BP/Process/MetadataBPProcess.rdf
- BP/SecuritiesIssuance/MetadataBPSecuritiesIssuance.rdf
- CAE/CorporateEvents/MetadataCAECorporateEvents.rdf
- CAE/MetadataCAE.rdf
- CIV/Funds/MetadataCIVFunds.rdf
- CIV/MetadataCIV.rdf
- LOAN/LoanContracts/MetadataLOANLoanContracts.rdf
- LOAN/LoanTypes/MetadataLOANLoanTypes.rdf
- LOAN/Loans/MetadataLOANLoans.rdf
- LOAN/LoansTemporal/MetadataLOANLoansTemporal.rdf
- LOAN/MetadataLOAN.rdf
- MD/CIVTemporal/MetadataMDCIVTemporal.rdf
- MD/DebtTemporal/MetadataMDDebtTemporal.rdf
- MD/DerivativesTemporal/MetadataMDDerivativesTemporal.rdf
- MD/MetadataMD.rdf
- MD/TemporalCore/MetadataMDTemporalCore.rdf
- catalog-v001.xml
Signed-off-by: Elisa Kendall ekendall@thematix.com
Revised metadata files so that the provisional ones were consistent with what we have in release, and to ensure that none are missing if one imports MetadataFIBO.  MetadataFIBO can be used together with AboutFIBODev to drive the FIBO viewer as a consequence.
Fixes: #993
> META-993 - MetadataFIBO does not load all of the FIBO content

- DER/DerivativesContracts/DerivativesBasics.rdf
Eliminated the redundant quantity value subclass relationship for ObservableValue.
Fixes: #999 / DER-67
> DER-67 - ObservableValue is redundantly declared to be a subclass of QuantityValue

- SEC/Securities/SecuritiesIdentification.rdf
Eliminates redundant registration scheme subclass relationships on two identification schemes
Fixes: #1001 / SEC-124
> SEC-124 - Redundant subclass relationships in Securities Identification should be eliminated

- SEC/Debt/Bonds.rdf
Eliminated the redundant subclass declaration on RegularCouponSchedule
Fixes: #1003 / SEC-125
> SEC-125 - Redundant subclass relationship in Bonds should be eliminated

- FBC/FunctionalEntities/RegulatoryAgencies.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
Eliminated redundant superclasses on FinancialServiceProvider and GovernmentIssuedLicense
Fixes: #1005 / FBC-250
> FBC-250 - Two classes in FBC have redundant subclass relationships that should be removed

- IND/EconomicIndicators/NorthAmericanIndicators/USEconomicIndicators.rdf
- IND/Indicators/Indicators.rdf
Eliminated redundant superclasses on MarketSpread a……nd UrbanConsumerPriceIndex
Fixes: #1007 / IND-94
> IND-94 - Two classes in IND have redundant subclass declarations that should be eliminated

- SEC/Debt/DebtInstruments.rdf
Integrated the new instrument pricing ontology with debt instruments, with security price as the parent of relative price, call price, and put price
Fixes: #1012
> SEC-126 - Call Price and Put Price should be subclasses of the new Security Price class

- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
- SEC/Securities/SecuritiesClassification.rdf
- SEC/Securities/SecuritiesIssuance.rdf
- SEC/Securities/SecuritiesListings.rdf
This initial PR reflects work-in-progress by the Securities FCT to augment the securities and equities ontologies to facilitate incorporation of the CFI codes for equities.  They represent a small subset of the CFI standard, but are important for several organizations participating in the FCT.
This initial pull request includes the additional concepts identified by the FCT to enable representation of the codes.  A subsequent pull request will include examples of the codes themselves classifying specific example instruments, to show FIBO users how to encode them for various applications.
Fixes: #1015  / SEC-73
> SEC-73 - Augment the equities concepts with their CFI classification

- AboutFIBODev.rdf
- AboutFIBOProd.rdf
- SEC/AllSEC-ReferenceIndividuals.rdf
- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityCFIClassificationIndividuals.rdf
- SEC/Securities/SecuritiesClassification.rdf
- catalog-v001.xml
Revises the equities module to add the actual CFI classification codes for an initial set of codes representing common shares and demonstrates their use in the example equities.
Fixes: #1015 / SEC-73
> SEC 73 - Augment the equities concepts with their CFI classification

- FND/Arrangements/Lifecycles.rdf
- FND/Utilities/AnnotationVocabulary.rdf
Eliminates skos:Concept as the superclass of MaturityLevel and replaces it with LifecycleStage; addresses issues raised about explanatory notes against FND-290 / pull request #922; corrects property hierarchy for adaptedFrom and logicalDefinition.
Fixes: #1022 / FND-293 and #922
> FND-293 - Correct subclass relation for MaturityLevel, subproperty hierarchy for adaptedFrom and logicalDefinition

- FND/Law/LegalCore.rdf
Corrected camel case naming of hasInForce (was hasInforce)
Fixes: #978 / FND-300
> FND-300 - hasInforce capitalization

- BE/OwnershipAndControl/CorporateOwnership.rdf
Revised the definition of beneficial owner to make it a subclass of controlling party rather than owner and add a restriction to indicate the asset that the beneficial owner controls
Fixes: #1029 / BE-212
> BE-212 - A beneficial owner is not an owner

- BE/OwnershipAndControl/CorporateControl.rdf
Revises the domain of a number of properties related to control to be LegalEntity rather than StockCorporation, as well as the definition of LegalEntity to add restrictions on those properties, as they are applicable to many different organizational structures and not limited to stock corporations
Fixes: #1027 / BE-211
> BE-211 - The domain of hasMajorityControllingInterestParty is StockCorporation, which is too narrow

- BE/OwnershipAndControl/ControlParties.rdf
- BE/OwnershipAndControl/OwnershipParties.rdf
Eliminated unused, redundant and logically inconsistent properties related to partial ownership
Fixes: #1034 / [BE-214](https://jira.edmcouncil.org/browse/BE-214)
> BE-214 - The semantics of isPartiallyOwnedBy and its subproperties and inverses are wrong

- BE/SoleProprietorships/SoleProprietorships.rdf
Eliminated redundant subclass declaration in sole proprietorship, enhanced ownership relations to take advantage of recent revisions to ownership parties, and revised definitions to be ISO 704 compliant
Fixes: #1037 / [BE-209](https://jira.edmcouncil.org/browse/BE-209)
> BE-209 - SoleProprietorship is redundantly declared to be a subclass of FormalOrganization

- BE/OwnershipAndControl/OwnershipParties.rdf
- FND/Parties/Parties.rdf
Completes the set of inverse relations needed to cover roles in situations with respect to independent parties; simplifies some of the property names and clarifies related definitions
Fixes: #1039 / BE-44
> BE-44 - Complete inverse relations for lattice and simplify property names

- BE/Partnerships/Partnerships.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf
Streamlined the partnerships ontology, eliminating categories of partnership that were defined exhaustively, but for which there are no known examples world-wide, loosening / refining restrictions and definitions, added new concepts and related definitions to correspond to the kinds of partnerships that actually do exist together with the roles that partners play in them, reworked definitions to be ISO 704 compliant and more representative of the concepts they apply to.
Fixes: #1041 / BE-216
> BE-216 - Partnerships are not well specified and partnership with general partners is overly constrained

- BE/LegalEntities/FormalBusinessOrganizations.rdf
- BE/LegalEntities/LegalPersons.rdf
- BE/OwnershipAndControl/Executives.rdf
Moved signatory related concepts to the executives ontology; in the context of the executives ontology: integrated the concept of authorization, authorizing/authorized parties, and related properties to enable better semantics of signatories and executives, simplified the ontology to eliminate some of the concepts around corporate officer duty and related obligations, revised definitions to be ISO 704 compliant
Fixes: #1044 / BE-217
> BE-217 - The definition of a signatory is disconnected from legally delegated authority and responsible party

- FND/Accounting/CurrencyAmount.rdf
- FND/Accounting/ISO4217-CurrencyCodes.rdf
Limited certain dependencies in currency amount and currency codes; replaced use of rdfs:comment with skos:definition in currency codes per FIBO policy
Fixes: #1048 / FND-258
> FND-258 - CurrencyCodes and CurrencyAmount ontologies have too many dependencies

- FND/Arrangements/Communications.rdf
- FND/Law/LegalCapacity.rdf
- FND/OwnershipAndControl/Control.rdf
- FND/OwnershipAndControl/Ownership.rdf
Replaced min 1 cardinality restrictions with someValuesFrom owl:Thing per policy (thus enabling addition of hygiene testing)
Fixes: #1052 / FND-301
> FND-301  - Eliminate references to min 1 cardinality

- AboutFIBODev.rdf
- AboutFIBOProd.rdf
- DER/AllDER-ExampleIndividuals.rdf
- DER/RateDerivatives/IRSwapExampleIndividuals.rdf
Adds a new example individuals ontology for interest rate swaps, representing a single, notional contract that is a fixed-float, single currency interest rate swap based on the example data the DER working group has been using, from Mizuho, to vet the IR Swap ontology and all of its dependencies, as well as a new load file that loads this new ontology as well as all of the other examples, reference data, and core FIBO ontologies in production
Fixes: #1046 / DER-72
> DER-72 - Incorporate the example interest rate swap contract corresponding to the standard reporting use case

- FND/Places/Addresses.rdf
Added missing imports of the Analytics ontology
Fixes: #1056 / FND-302
> FND-302 - Addresses is missing an import

- BE/OwnershipAndControl/CorporateControl.rdf
This resolution addresses some of the confusing issues related to affiliation and controlling interest parties in BE.  It refines the concept of an affiliate to indicate which is controlling or controlled, adds an affiliation situation which allows for the representation of the time period and percentage ownership, if applicable, and adds properties that enable identification of which party is in which role in an affiliation, integrates the notion of a subsidiary, and eliminates unused and confusing classes and properties related to controlling interest.  As a result, reasoning results are much better, affiliation is inferred for our example organizations, and the resulting graph makes much more sense.
Details related to controlling interest that we are still using have been retained, …
> BE-192 - Revise the definition of Affiliate to make more sense

- BE/OwnershipAndControl/Executives.rdf
Adds the concept of board membership and a number of properties linking corporate officers and directors to the organizations they manage; clarifies a couple of additional definitions
Fixes: #1062
> BE-219 - Definitions related to board membership need to be better integrated

- etc/testing/hygiene/testHygiene1067.sparql
See:  https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t1-polysemous-elements
Signed-off-by: Robert Trypuz <robert.trypuz@makolab.com>
Fixes: #1067
> Extending the set of hygiene test by implementing a test candidate T1

- DER/DerivativesContracts/Options.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
- FND/Arrangements/Arrangements.rdf
- FND/Arrangements/ClassificationSchemes.rdf
- FND/DatesAndTimes/FinancialDates.rdf
- FND/OwnershipAndControl/Ownership.rdf
- FND/Relations/Relations.rdf
- FND/Utilities/Analytics.rdf
- IND/Indicators/Indicators.rdf
- IND/MarketIndices/BasketIndices.rdf
- MD/DebtTemporal/DebtAnalytics.rdf
- SEC/Securities/Baskets.rdf
Certain classes, and properties, e.g., DatedCollectionConstituent in Arrangements, used a union of several datatypes (exactly those defined in the CombinedDateTime datatype in FinancialDates), which causes reasoning and efficiency challenges.  This resolution addresses that by moving those concepts to FinancialDates, eliminating those issues and improving usability. (Relates to issue #1043 and FND-242)
In the process of addressing this, we have eliminated circular dependencies in definitions in the ontologies this issue touches, as identified in issue #1050.
Fixes: #1070 / FND-242
> FND-242 Undesirable dependencies in FND ontologies

- SEC/Debt/Bonds.rdf
Replaced the isBasedOn property in Bonds, which was a duplicate of isBasedOn in Debt, with the property of the same name from the Debt ontology
Fixes: #1090 / SEC-127
> SEC-127 - Eliminate duplicate isBasedOn property in the Bonds ontology

- DER/DerivativesContracts/Swaps.rdf
- DER/RateDerivatives/IRSwaps.rdf
Replaced the duplicate hasPaymentSchedule property ……in Swaps and IRSwaps with the corresponding property from FND; moved notes from the property definition to the class where it is used in a restriction, namely FixedPaymentLeg, as they provide additional context that should have been associated with the class, rather than with the property, from the outset and massaged the definition of that class accordingly and so that it is no longer circular.
Fixes: #1092 / DER-73
> DER-73 - Eliminate duplicate hasPaymentSchedule property in Swaps

- BE/LegalEntities/NorthAmericanEntities/USExampleEntities.rdf
- DER/DerivativesContracts/SwapsIndividuals.rdf
- DER/RateDerivatives/IRSwapExampleIndividuals.rdf
- FBC/FunctionalEntities/BusinessRegistries.rdf
- FBC/FunctionalEntities/EuropeanEntities/EURegulatoryAgencies.rdf
- FBC/FunctionalEntities/EuropeanEntities/EuropeanFinancialServicesEntitiesIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USMarketsAndExchangesIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
- FND/Arrangements/Ratings.rdf
- FND/Places/NorthAmerica/USPostalServiceAddresses.rdf
- FND/ProductsAndServices/ProductsAndServices.rdf
- FND/Relations/Relations.rdf
- IND/InterestRates/MarketDataProviders.rdf
- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityCFIClassificationIndividuals.rdf
- SEC/Securities/SecuritiesClassification.rdf
Eliminate remaining references to fibo-fnd-rel-rel:hasTag in favor of lcc-lr:hasTag, and remove the relations property.  This property was created to cover complex datatypes in addition to strings as the basis for any code or identifier, which in practice has been unnecessary.  If corner cases arise over time that require binary data tags, we should create separate properties to address them.  Eliminating this union in the range of hasTag reduces reasoning complexity as well as removing a duplicate property name more generally.
Fixes: #1082 / FND-305 - also relates to #1043
> FND-305 - Eliminate reasoning complexity due to the union in hasTag in the relations ontology

- FND/DatesAndTimes/FinancialDates.rdf
- FND/DatesAndTimes/Occurrences.rdf
Eliminate unnecessary unions in restrictions in occurrences; note that there is one remaining union in a restriction in this ontology, on the occurrence class, which is definitional and thus retained.
Fixes: #1084 / FND-307; also relates to #1043
> FND-307 - Eliminate unnecessary unions in restrictions in the Occurrences ontology

- BE/OwnershipAndControl/OwnershipParties.rdf
- FND/Parties/Parties.rdf
Renamed property hasPrimaryParty to hasActiveParty as suggested
Fixes: #1077 / FND-309
> FND-309 - Inconsistent labeling / naming of party relationships in the new extended lattice

- FND/Places/Addresses.rdf
- FND/Places/NorthAmerica/USPostalServiceAddresses.rdf
Eliminated most unions and max 1 cardinality restr……ictions in the addresses ontology to allow for more options for address representation and increase reasoning efficiency; fixed wrong label in the US-specific extension
Fixes: #1098
> FND-308 - Eliminate unnecessary unions and max 1 restrictions in the addresses ontologies

- etc/testing/hygiene/testHygiene1078.sparql
This check is to warn that there are object properties with multiple inverses.
Fixes: #1078
> Extending hygiene tests set - no property may have more than one inverse

- etc/testing/hygiene/testHygiene1067.sparql
- etc/testing/hygiene/testHygiene1068.sparql
- etc/testing/hygiene/testHygiene1078.sparql
- etc/testing/hygiene/testHygiene1079.sparql
banner keyword was added to new hygiene SPARQL tests to facilitate interpretation of tests' results in Jenkins.
Fixes: #1112
> Add banner keyword to new hygiene tests

- BP/SecuritiesIssuance/IssuanceDocuments.rdf
- FBC/DebtAndEquities/Debt.rdf
- SEC/Debt/AssetBackedSecurities/AssetBackedSecurities.rdf
- SEC/Debt/Bonds.rdf
- SEC/Debt/DebtInstruments.rdf
- SEC/Securities/SecuritiesIssuance.rdf
Revised the debt terms / redemption terms hierarch……y to make redemption provision a direct subclass of contractual commitment rather than of principal repayment terms, given that it applies to preferred shares; refactored the conversion and redemption provisions more generally and eliminated a couple of unneeded intervening classes that were not widely used and that didn't have restrictions that we need.
Fixes: #1110 / FBC-257
> FBC-257 - Redemption provisions should apply at the instrument level, and may not necessarily involve 'principal repayment'

- BE/GovernmentEntities/GovernmentEntities.rdf
- BE/OwnershipAndControl/Executives.rdf
- BP/SecuritiesIssuance/EquitiesIPOIssuance.rdf
- FBC/FunctionalEntities/RegistrationAuthorities.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- FND/Relations/Relations.rdf
- FND/Utilities/Analytics.rdf
- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
Removed 'Reference' as the domain of several properties; eliminated a redundant 'evaluates' property from Analytics that was not used anywhere; adjusted definitions for a few properties in Relations that were not ISO 704 compliant
Fixes: #1095 / [FND-306](https://jira.edmcouncil.org/browse/FND-306)
> FND-306 - The domain of of several properties should not be 'Reference', which is too narrow

- etc/testing/hygiene/testHygiene0114.sparql
Signed-off-by: Pawel Garbacz pawel.garbacz@makolab.com
This pr downgrades the level of the bad character check to warnings and refactors the warning messages so that the first word in them is 'WARN'.
Fixes: #1119
> Fix to bad characters check

- etc/testing/hygiene/testHygiene1103.sparql
https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md#t2-synonyms-as-classes suggests a test to find all equivalent named classes as they may indicate that synonyms were modelled as separated classes, which is not consistent with FIBO conventions.
This pr is to implement this test.
Fixes: #1103
> Tests for Quality Compliance - Synonyms as classes

- IND/EconomicIndicators/EconomicIndicators.rdf
Augmented economic indicators to include information regarding part-time employment and underemployment
Fixes: #1142 / IND-98
> IND-98 - Missing concepts related to part-time employment and underemployment

- FND/Quantities/QuantitiesAndUnits.rdf
- FND/Utilities/Analytics.rdf
Eliminated the redundant rate class, added rate as a synonym on ratio, and eliminated the circularity in the definition of standard deviation
Fixes: #1147 / FND-315
> FND-315 - The Rate class in Quantities and Units is redundant with Ratio in Analytic

- etc/testing/hygiene/testHygiene1127.sparql
This is to warn about all definitions that contain the "or" connective.
Fixes: #1127
> Hygiene check for disjunctive definitions

- AboutFIBODev.rdf
- BE/FunctionalEntities/FunctionalEntities.rdf
- FBC/FunctionalEntities/FinancialServicesEntities.rdf
- FBC/ProductsAndServices/CardAccounts.rdf
- FBC/ProductsAndServices/ClientsAndAccounts.rdf
- FBC/ProductsAndServices/MetadataFBCProductsAndServices.rdf
- FND/Arrangements/Documents.rdf
- FND/Relations/Relations.rdf
- catalog-v001.xml
This resolution refines concepts related to accounts, including new concepts covering account statements, transaction records, individual transactions, and cleans up a number of definitions related to accounts based on user experiences.  It renames FinancialServiceAccount to CustomerAccount to improve user understanding, and extends the concept of a customer account to include card accounts (credit card account and debit card account).  It relates a card account to a card product, including classifying card products by network.  It relates a card account to the payment card (debit or credit), and supports common features of such cards, including the primary card account number (PAN), expiration date, and security code based on the international standard (see …
> FBC-260 - Need the ability to represent credit card accounts

- AboutFIBOProd.rdf
- IND/AllIND-ExampleIndividuals.rdf
- IND/AllIND.rdf
- IND/MarketIndices/BasketIndices.rdf
- IND/MarketIndices/EquityIndexExampleIndividuals.rdf
- IND/MarketIndices/MetadataINDMarketIndices.rdf
Now that the Credit Events ontology is available in release, this resolution integrates the market indices and examples ontologies, which depend on credit events, into release.
Fixes: #1167 / IND-99
> IND-99 - Revise the market baskets and benchmark examples for release

- DER/SecurityBasedDerivatives/EquityForwards.rdf
- DER/SecurityBasedDerivatives/EquitySwaps.rdf
- DER/SecurityBasedDerivatives/SecurityBasedDerivatives.rdf
Eliminated additional unused and duplicate classes in security-based and equity swaps as well as in equity forwards, cleaned up more of the terminology based on FCT discussion
Fixes: #1173 / DER-75
> DER-75 - Additional clean-up is needed in the SecurityBasedSwaps and EquitySwaps

- BE/OwnershipAndControl/CorporateOwnership.rdf
- BE/OwnershipAndControl/OwnershipParties.rdf
- FBC/ProductsAndServices/CardAccounts.rdf
- FBC/ProductsAndServices/ClientsAndAccounts.rdf
- FND/Parties/Parties.rdf
Added top level AccountOwnership related classes to better integrate account holder relations with the situational patterns, cleaned up content that wasn't used and didn't align with the pattern, including cleaning up the corresponding pattern for shareholder/shareholding ownership related content.
Fixes: #1178 / FBC-261
> FBC-261 - Need better and complete alignment of account and account-related properties with the situation pattern

- SEC/Securities/SecuritiesIdentification.rdf
Added reassignable identifier as a parent of ticker symbol, loosened the restriction on linking the symbol to the instrument, and cleaned up ambiguous definitions
Fixes: #1180 / SEC-128
> SEC-128 - A ticker symbol can identify more than one listing over time, even on the same exchange

- SEC/Debt/Bonds.rdf
There were over 40 circular and/or ambiguous definitions in the bonds ontology.  This resolution eliminates most of them.
Fixes: #1182  / SEC-133
> SEC-133 - Eliminate circular and ambiguous definitions in Bonds

- BE/FunctionalEntities/FunctionalEntities.rdf
Eliminated smart quote in the definition of family office and the ambiguity in the definition of has merchant category description
Fixes: #1184 / BE-227
> BE-227 - Editorial correction to eliminate a smart quote in the definition of family office

- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
Added a property to represent the share class and used it in individuals for Alphabet shares to provide an example of how to use it
Fixes: #1145 / SEC-139
> SEC-139 - FIBO is lacking a specific property to represent share class

- etc/testing/hygiene/testHygiene1190.sparql
This PR adds a check for cycles in class hierarchy.
It is to be run as SPARQL query in an environment without reasoning capabilities or with reasoning disabled, e.g., in Jena ARQ.
Fixes: #1190
> Hygiene test for class hierarchy cycles

- FND/Accounting/AccountingEquity.rdf
- SEC/Securities/Pools.rdf
Added the concept of a physical asset as being disjoint from financial asset; Cleaned up definitions in the accounting equity ontology that were circular or ambiguous in some way and eliminated the redundant and confusing takesForm property in favor of hasMonetaryAmount.
Fixes: #1196 / FND-319
> FND-319 - Missing the concept of a physical asset as a sibling of financial asset

- etc/testing/hygiene/testHygiene1190_properties.sparql
This PR adds a check for cycles in property hierarchy.
It was suggested by @rivettp as a twin to the check discussed in https://github.com/edmcouncil/fibo/issues/1190.
Fixes: #1190
> New hygiene test - property hierarchy cycles

- etc/testing/hygiene/testHygiene1177.sparql
Signed-off-by: Pawel Garbacz pawel.garbacz@makolab.com
This adds a check that identifies every ontology that imports itself.
Fixes: #1177
> New hygiene test - direct circularity in owl imports

- FBC/FinancialInstruments/FinancialInstruments.rdf
Added a new property, isDenominatedIn, and a restriction on FinancialInstrument indicating the currency that the instrument is denominated in.  This was available implicitly through the jurisdiction before, but we have made it explicit.
Fixes: #1208 /FBC-254
> FBC-254 - Need to be able to say what currency an instrument is issued in

- BE/LegalEntities/LegalPersons.rdf
- BE/OwnershipAndControl/CorporateOwnership.rdf
- CIV/Funds/CIV.rdf
- DER/DerivativesContracts/RightsAndWarrants.rdf
- FBC/DebtAndEquities/Guaranty.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FND/Agreements/Contracts.rdf
- MD/CIVTemporal/FundsTemporal.rdf
- SEC/Debt/AssetBackedSecurities/CDOs.rdf
- SEC/Securities/SecurityAssets.rdf
The current contract party hierarchy is overly complicated and should be streamlined for ease of representing parties to a contract.  This issue cleans that up, eliminating concepts that had no additional semantics, such as transferable contract holder, security holder, and contract originator in favor of contract principal (retaining loan originator, however, which has specific meaning in the context of loans).  It adds a missing restriction on contract party, which was duplicated on some subclasses, and also cleans up ambiguous definitions in the contracts ontology to the degree that is feasible.
Fixes: #1212 / FND-322
> FND-322 - Contract party is missing a restriction and the class hierarchy related to contract parties is overly complex

- DER/CommoditiesDerivatives/CommodityOptions.rdf
- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/DerivativesMasterAgreements.rdf
- DER/DerivativesContracts/Forwards.rdf
- DER/DerivativesContracts/Options.rdf
- DER/DerivativesContracts/Spots.rdf
- DER/DerivativesContracts/Swaps.rdf
- DER/ExchangeTradedDerivatives/ExchangeTradedOptions.rdf
- DER/RateDerivatives/IROptions.rdf
- DER/SecurityBasedDerivatives/BondOptions.rdf
- DER/SecurityBasedDerivatives/EquityOptions.rdf
This resolution takes advantage of recent streamlining in FND with respect to contract parties, and takes it a step further to clean up the derivatives contract party hierarchy as well as to simplify out a number of redundant elements (classes and properties) related to Options in particular.
Fixes: #1214 / DER-83
> DER-83 - Simplify the contract party tree in derivatives

- etc/testing/hygiene/testHygiene1198_dev.sparql
- etc/testing/hygiene/testHygiene1198_prod.sparql
This pull request adds a check that finds dots in local names of FIBO classes and properties.
Due to the current state of the infrastructure it is split into two checks:
1. one check raises warnings for DEV
2. the other check raises errors in PROD.
Fixes: #1198
> New hygiene test - dots in local names of FIBO classes and properties

- BE/LegalEntities/FormalBusinessOrganizations.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
- FBC/FunctionalEntities/RegulatoryAgencies.rdf
- FND/Law/Jurisdiction.rdf
- FND/Parties/Parties.rdf
Augments FormalBusinessOrganizations to represent the concept of a tax identifier for any independent party as well as a value-added tax identifier (i.e., VAT); augments the USRegulatoryAgencies ontology to add TIN and EIN for AML/KYC purposes; addresses a handful of ambiguous definitions
Fixes: #1221 / BE-106
> BE-106 - Need the concept of a tax identifier to support AML and other use cases

- SEC/Equities/EquityCFIClassificationIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
Added subclasses to cover share payment status to eliminate the need for certain restrictions on CFI individuals
Fixes: #1234 / SEC-73
> SEC-73 - Build out the classes related to payment status of shares

- FBC/FinancialInstruments/InstrumentPricing.rdf
- FND/DatesAndTimes/FinancialDates.rdf
Added two properties to financial dates for opening and closing date, time, as well as an individual duration for 'day'; extended instrument pricing to include trading day and session, and revised ambiguous definitions
Fixes: #1232 / SEC-142
> SEC-142 - Need the concept of a trading day, as a subclass of date period

- SEC/Securities/SecuritiesIdentification.rdf
- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
- SEC/Securities/SecuritiesListings.rdf
Eliminated confusion between listed security and listing which caused reasoning errors, corrected ticker symbol as identifying a listed security rather than listing, streamlined hierarchy for registered securities, and eliminated ambiguity in definitions
Fixes: #1244 / SEC-145
> SEC-145 - Listed security is improperly inferred to be a listing

- BE/LegalEntities/CorporateBodies.rdf
- BE/OwnershipAndControl/OwnershipParties.rdf
Eliminated unnecessary subclasses of corporation that either reflect non-existent kinds of organizations or add clutter with respect to guarantees that can be addressed simply by linking a guarantee to the instrument of incorporation, including relationships with guarantors
Fixes: #1257 / BE-137
> BE-137 - There are no known instances of bodies incorporated through agreement

- AboutFIBOProd.rdf
- DER/AllDER-ExampleIndividuals.rdf
- DER/AllDER-ReferenceIndividuals.rdf
- DER/AllDER.rdf
- DER/MetadataDER.rdf
- DER/SecurityBasedDerivatives/EquitySwaps.rdf
- DER/SecurityBasedDerivatives/SecurityBasedDerivatives.rdf
This issue updates two of the security-based derivatives ontologies, the core ontology and equity swaps, to change their status to 'release', and updates metadata and 'load' ontologies accordingly
Fixes: #1251
> Release the provisional SecurityBasedDerivatives and EquitySwaps ontologies

- BE/Trusts/Trusts.rdf
Added several kinds of trusts, refined definitions based on multiple sources and moved some content to explanatory notes, improved integration of trust parties, cleaned up unused concepts
Fixes: #1259  / BE-229
> BE-229 - A number of key classes are missing in the trusts ontology

- BE/OwnershipAndControl/ControlParties.rdf
- BE/PrivateLimitedCompanies/PrivateLimitedCompanies.rdf
Adds a number of missing concepts to the PrivateLimitedCompanies ontology, including limited liability company (LLC), limited liability company member, limited liability company taxed as a corporation (C-LLC), manager-managed limited liability company, managing member, private limited company (Ltd.), and properties linking a managing member to the limited liability company they manage.
Fixes: #1264 / BE-218
> BE-218 - Need the role of managing member associated with an LLC

- etc/testing/hygiene/testHygiene1068.sparql
This is to remove false positives in the check for circular definitions.
Fixes: #1261
> Fix to the test on circular definitions

- FBC/FinancialInstruments/InstrumentPricing.rdf
Added AdjustedClosingPrice as well as a more general ClosingPrice, and made OfficialClosingPrice a subclass of closing price, with an explanatory note.
Fixes: #1134 / SEC-147
> SEC-147 - FIBO does not allow representation of adjusted and unadjusted prices for equities

- FBC/FunctionalEntities/EuropeanEntities/EuropeanFinancialServicesEntitiesIndividuals.rdf
- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
Added SIX FinancialInformation AG (the issuer) and SIX Group AG to the European financial services entities individuals and updated LEI data for the individuals represented in this ontology to reflect the latest GLEIF published LEI data; completed the details for the Telekurs Id and added the Valoren to the securities identification individuals.
Fixes: #1268 / DER-71
> DER-71 - Need the definition of a valoren as an instrument identifier

- DER/DerivativesContracts/Forwards.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
- SEC/Securities/SecuritiesListings.rdf
Added new property hasLotSize as the superproperty of hasQuoteLotSize to instrument pricing; added a restriction in securities listings on listing to say that a listing might have a lot size associated with it and added a usage note on listed security regarding multiple classification of individuals.
Fixes: #1270 / SEC-146
> SEC-146 - Need to add a property for the lot size on listing

- FND/AgentsAndPeople/People.rdf
- FND/Agreements/Contracts.rdf
Added explicit DateOfBirth, DateOfDeath, PlaceOfBirth, and concepts related to death certificates; streamlined restrictions and properties accordingly
Fixes: #1017 / FND-325
> FND-325 - Need explicit definitions of DateOfBirth and DateOfDeath

- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityCFIClassificationIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
- SEC/Securities/SecuritiesIssuance.rdf
- SEC/Securities/SecuritiesListings.rdf
Streamlined representation of the registered form of shares in securities issuance and securities listings and incorporated the concept of a book entry form; adjusted definitions in securities issuance to eliminate ambiguity, revised equity instruments to eliminate restrictions made redundant by the changes, revised CFI and example individuals to incorporate the changes and augment the equities examples with additional content; also cleaned-up delisting date and isTradedOn based on FCT discussion
Fixes: #1273 / SEC-107 / SEC-129
> SEC-107 - Distinctions between the various ways that a security may be registered / listed are missing or need revision

- BE/FunctionalEntities/FunctionalEntities.rdf
- BE/OwnershipAndControl/ControlParties.rdf
- BE/OwnershipAndControl/Executives.rdf
- BE/PrivateLimitedCompanies/PrivateLimitedCompanies.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FBC/FunctionalEntities/FinancialServicesEntities.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
Added a number of missing entities, including Association, Development Bank, Money Services Business, Mortgage Company, Registered Investment Advisor, Federal Government Entity and State Government Entity, as well as incorporating the concept of a principal party, and introducing pairs of properties linking various entities and parties through the party lattice that were gaps
Fixes: #1275 / FBC-267
> FBC-247 - Missing financial services and US government entities

- ONTOLOGY_GUIDE.md
This pull request removed the description of the T8 test candidate from the Ontology Guide - as per discussion in issue #1193.
Fixes: #1193
> T8 Test Candidate removed from Ontology Guide

- FBC/ProductsAndServices/ClientsAndAccounts.rdf
Revised the definition of customer account to generalize it per user suggestions and adjusted / cleaned-up a few others to eliminate ambiguity, etc.
Fixes: #1280 / FBC-266
> FBC-266 - The name of the class 'financial service account' was changed to 'customer account' but the definition is still too narrow

- FBC/DebtAndEquities/Guaranty.rdf
Added de jure controlling interest party as a parent of guarantor, introduced two additional properties linking the controlled party to the controlling party (the guarantor) to hook the concept of a guarantor into the control party lattice, cleaned up and eliminated ambiguity in definitions
Fixes: #1282 / FBC-269
> FBC-269 - Missing properties in the Guaranty ontology

- FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf
- FND/DatesAndTimes/FinancialDates.rdf
This turned out to be somewhat misleading, caused by hasExplicitDate being declared as functional in FND.  When we changed hasDateEstablished and hasDateInsured to have a range of explicit date (which they should have been all along), and made the properties subproperties of hasExplicitDate, rather than hasDate, the bug (which was in the FinancialDates ontology for many years) became obvious.  That declaration was removed in the context of correcting this error.
Fixes: #1286
> Correct reasoning issue in FBC US Examples related to hasDateEstablished

- ONTOLOGY_GUIDE.md
The test for incomplete modelling removed from the list of test candidates.
Fixes: #1191
> Test candidate T6 removed from ontology guide

- FBC/FinancialInstruments/FinancialInstruments.rdf
- LOAN/LoanContracts/LoanCore.rdf
- SEC/Debt/DebtInstruments.rdf
- SEC/Equities/EquityInstruments.rdf
Moved the property hasMaturityDate from DebtInstruments to FinancialInstruments as it can apply to preferred shares as well as to debt and other instruments, eliminated the redundant hasScheduledMaturityDate property, added an optional restriction to preferred share indicating that it can have a maturity date, added the definition for a retractable preferred share; also added a synonym of extendible preferred share to extendable preferred share.
Fixes: SEC-136 
Fixes: #1136 
Fixes: #1137
> SEC-136 - Unclear coverage of RetractablePreferredShare

- etc/testing/hygiene/testHygiene1290.sparql
Signed-off-by: Pawel Garbacz pawel.garbacz@makolab.com
This test finds all top-level classes outside FND, FBC and LCC domains.
Fixes: #1290
> New hygiene test - Test for diconnected elements

- FND/Places/Facilities.rdf
Eliminated circular and ambiguous definitions in the Facilities ontology, restated them to conform with ISO 704, and simplified the ontology by merging physical site with site
Fixes: #1297 / FND-329
> FND-329 - Several definitions in the Places/Facility ontology are flagged as circular and should be corrected

- FBC/FinancialInstruments/InstrumentPricing.rdf
- FND/Accounting/CurrencyAmount.rdf
- FND/Utilities/Analytics.rdf
Eliminated the redundant calculation formula class from Analytics and replaced it with formula in the few places it is used
Fixes: #1301 / FND-327
> FND-327 - Calculation formula is redundant with formula

- BE/OwnershipAndControl/ControlParties.rdf
Corrected label on hasControllingOrganizationMember
Fixes: #1303 / BE-231
> BE-231 - Wrong label on hasControllingOrganizationMember

- BE/GovernmentEntities/EuropeanJurisdiction/EUGovernmentEntitiesAndJurisdictions.rdf
Removed the UK from the EU jurisdiction / coverage and revised references to the Czech Republic to be Czechia
Fixes: #1305 / BE-208
> BE-208 - The EU jurisdiction individuals include the UK and should not

- BE/PrivateLimitedCompanies/PrivateLimitedCompanies.rdf
Eliminated the smart quote in the explanatory note on manager-managed limited liability company
Fixes: #1307 / BE-232
> BE-232 - Smart quote in a note in private limited companies

- etc/testing/hygiene/testHygiene1289.sparql
This test searches for object properties that may be isA impostors.
As per discussion in the [underlying issue](https://github.com/edmcouncil/fibo/issues/1289) the search looks for object properties whose local names:
- are identical to 'isA' string
- start with 'may' string 
- contain either 'become' or 'also' strings.
Fixes: #1289
> Hygine test for isA candidates

- etc/testing/hygiene/testHygiene1293.sparql
This test searched for the min 1 cardinality restrictions - both qualified and non-qualified.
Fixes: #1293
> Test for "min 1" cardinality restrictions

- etc/testing/hygiene/testHygiene1292.sparql
This test is to find classes that refer to multiple concepts by means of the logical constructs of conjunctions and disjunctions.
Fixes: #1292
> New hygiene test -  Classes referring to multiple concepts added

- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- DER/DerivativesContracts/Forwards.rdf
- DER/DerivativesContracts/Options.rdf
- DER/ExchangeTradedDerivatives/ExchangeTradedOptions.rdf
- FND/ProductsAndServices/ProductsAndServices.rdf
Added the concept of a sale, and properties including hasBuyer and hasSeller, and cleaned up circular and ambiguous definitions in the FND Products and Services ontology; replaced several hasBuyer and hasSeller properties defined in derivatives ontologies with the new properties in FND.
Fixes: #1310 / FND-323
> FND-323 - Need new properties for hasBuyer and hasSeller in the Products and Services ontology

- BE/Corporations/Corporations.rdf
- BE/FunctionalEntities/Publishers.rdf
- BE/GovernmentEntities/GovernmentEntities.rdf
- BE/LegalEntities/LegalPersons.rdf
- BE/OwnershipAndControl/CorporateOwnership.rdf
- BE/OwnershipAndControl/Executives.rdf
- BE/Trusts/Trusts.rdf
- FBC/FunctionalEntities/FinancialServicesEntities.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- FND/Accounting/CurrencyAmount.rdf
- FND/Agreements/Contracts.rdf
- FND/Arrangements/Documents.rdf
- FND/Arrangements/Lifecycles.rdf
- FND/Arrangements/Reporting.rdf
- FND/OwnershipAndControl/Control.rdf
- IND/EconomicIndicators/EconomicIndicators.rdf
In order to address these now bad links, eliminated references to external dictionaries that no longer resolve, corrected circular definitions in several of the ontologies that these references impacted, and eliminated a redundant property in currency amount (whose definition was circular)
Fixes: #1316 / FND-328
> FND-328 - Two of the public dictionary sites referenced in FIBO have been taken down and references no longer resolve

- FBC/DebtAndEquities/Debt.rdf
- FND/Agreements/Contracts.rdf
- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityCFIClassificationIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
Augmented the reference Equity CFI Classification ontology to include a complete set of classes covering sections 6.2.2 Equities - Common/ordinary shares and 6.2.3 Equities - Preferred/preference shares, for those that are classified as registered securities with respect to the fourth attribute.  This does not yet include all of the codes for preferred shares, only those that apply to common shares.  We anticipate building out those codes as well as the classes covering sections 6.2.4 Equities - Common/ordinary convertible shares, and 6.2.5 Equities - Preferred/preference convertible shares over the coming months.
Note that this change adds 196 classes for preferred shares alone, and, due to numerous hasValue restrictions, increases the …
> SEC-73 - An exhaustive set of classes, corresponding to the various equity feature combinations expressed in the CFI standard are needed

- FBC/FinancialInstruments/FinancialInstruments.rdf
- FBC/FunctionalEntities/BusinessRegistries.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntities.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
The resolution to this issue eliminates circular and some ambiguous definitions from FinancialInstruments and certain FBC/FunctionalEntities ontologies that have been flagged in hygiene testing. It also modifies or eliminates references to external definitions that are either not directly quoted or are not relevant. 
Note that some of the references are also mentioned in #1321, which has broader scope.
Fixes: #1324 / FBC-270
> FBC-270 - There are a number of circular definitions in FBC that should be resolved

- BP/SecuritiesIssuance/AgencyMBSIssuance.rdf
- BP/SecuritiesIssuance/DebtIssuance.rdf
- BP/SecuritiesIssuance/PrivateLabelMBSIssuance.rdf
- FND/Relations/Relations.rdf
In Relations, cleaned up references to external dictionaries that don't meet FIBO policies, eliminated ambiguity in definitions where possible, eliminated the superproperties of produces and is produced by whose semantics are different from their parent properties, and improved ISO 704 compliance of definitions; Elsewhere - cleaned up references to external dictionaries that don't meet FIBO policies and eliminated a few duplicate properties uncovered during review
Note that the other remaining references were addressed under FBC-270 / #1325 
Fixes: #1321 / FND-331
> Problematic sources in citations

- BE/GovernmentEntities/GovernmentEntities.rdf
- BE/GovernmentEntities/NorthAmericanJurisdiction/CAGovernmentEntitiesAndJurisdictions.rdf
- BE/GovernmentEntities/NorthAmericanJurisdiction/MXGovernmentEntitiesAndJurisdictions.rdf
- DER/DerivativesContracts/Swaps.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- SEC/Debt/AssetBackedSecurities/AssetBackedSecurities.rdf
- SEC/Debt/AssetBackedSecurities/CDOs.rdf
- SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf
- SEC/Debt/DebtInstruments.rdf
Several properties in production violated our new hygiene test regarding the use of "may", "isAlso", "isA" and similar phrases, including 'mayBeTradedIn', which was eliminated in favor of the appropriate properties of listings in SEC, 'mayBeSubordinatedTo', which was renamed 'isSubordinatedTo', and 'hasPartialSovereigntyOver', which has an embedded 'also' that triggered the test.  In the case of the latter, because it was very similar to 'hasSharedSovereigntyOver' and sparsely used, we replaced 'hasPartialSovereigntyOver' with shared sovereignty and eliminated the challenge with 'also'.
Note that there a quite a few similar issues in provisional, which will be addressed as time permits and when other issues with those ontologies are …
> FBC-271 - Eliminate properties that include "may", "is also" and similar phrases, which violate our hygiene test for masquerading properties

- BE/AllBE-NorthAmerica.rdf
- BE/GovernmentEntities/NorthAmericanJurisdiction/CaribbeanGovernmentEntitiesAndJurisdictions.rdf
Revised the prefix for the Caribbean government entities to conform with our naming conventions and addressed issues with diacritical language symbols
Fixes: #1314 / BE-224
> BE-224 - Typo in ontology prefix: fibo-ge-ge-cbj

- BE/GovernmentEntities/EuropeanJurisdiction/EasternEuropeGovernmentEntitiesAndJurisdictions.rdf
- BE/GovernmentEntities/EuropeanJurisdiction/NorthernEuropeGovernmentEntitiesAndJurisdictions.rdf
- BE/GovernmentEntities/EuropeanJurisdiction/SouthernEuropeGovernmentEntitiesAndJurisdictions.rdf
Eliminates language-specific diacritical markings in definitions of governments and jurisdictions for the EU; adds language-specific labels to government entities, governments and jurisdictions using the languages suggested as administrative for that country by the U.N.
Fixes: #1333 / BE-224
> Correct hygiene issues related to diacritical markings in various government and jurisdiction ontologies

- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
Eliminated long dashes in a note on the Valoren and a few unnecessary references to external sources
Fixes: #1335 / DER-71
> DER-71 - Correct hygiene issue in an explanatory note on the Valoren instrument identifier

- SEC/Debt/Bonds.rdf
- SEC/Debt/DebtInstruments.rdf
- SEC/Debt/TradedShortTermDebt.rdf
- SEC/Securities/ParametricSchedules.rdf
- SEC/Securities/SecuritiesListings.rdf
This resolution corrects circular definitions in debt instruments, parametric schedules and traded short-term debt.  It also eliminates false positive hygiene results for several classes in SEC (in bonds and securities listings) whose names included 'and' but that, in fact, defined singular concepts.
Note that there is one class remaining in the Bonds ontology that actually needs to be split into multiple concepts and that still includes 'and' in its name, which should be addressed in a separate resolution.
Fixes: #1340 / SEC-118
> SEC-118 - Eliminate remaining circular definitions and other hygiene violations in the SEC ontologies

- etc/testing/hygiene/testHygiene0114.sparql
- etc/testing/hygiene/testHygiene1289.sparql
- etc/testing/hygiene/testHygiene1290.sparql
Three hygiene tests can be promoted to prod errors.
Fixes: #1342
> Three hygiene tests can be promoted to prod errors

- SEC/Equities/EquityInstruments.rdf
Added a property for specifying the number of authorized shares and restriction on equity issuer saying that they have to have authorized at least some number of shares to be an issuer; adjusted the definition of has shares issued to eliminate confusion between that property and shares authorized.
Fixes: #1344 / SEC-149
> SEC-149 - Need a property in equities representing the authorized number of shares

- FND/Utilities/Analytics.rdf
Eliminate the property hasOperand, which is not used anywhere and whose definition is circular
Fixes: #69 / FND-332
> FND-332 - Circular definition for hasOperand

- FBC/DebtAndEquities/Debt.rdf
- FBC/FunctionalEntities/EuropeanEntities/EUFinancialServicesEntities.rdf
Eliminated remaining hygiene issues in FBC, including circular definitions in properties in Debt and renaming the CreditInstitutionOrInvestmentFirm class to eliminate the 'or' in European functional entities, adjusting its label and definition accordingly
Fixes: #1351 / FBC-274
> FBC-274 - Eliminate remaining circular definitions and naming related hygiene issues in FBC

- FND/Arrangements/ClassificationSchemes.rdf
- FND/Arrangements/Ratings.rdf
- FND/DatesAndTimes/BusinessDates.rdf
- FND/OwnershipAndControl/OwnershipAndControl.rdf
- FND/Parties/Roles.rdf
- FND/Places/Addresses.rdf
- FND/ProductsAndServices/PaymentsAndSchedules.rdf
- FND/Quantities/QuantitiesAndUnits.rdf
Hygiene testing has identified 7 remaining immediately circular definitions and 3 cases where class or property names might indicate that a given element refers to multiple concepts in FND (released ontologies), which should be remedied.  The resolution to this issue adjusted the relevant definitions to eliminate the circularities, renamed 3 classes to eliminate the ambiguity in their names and improved integration of ownership and control concepts with the situation pattern.
Fixes: #1374 / FND-333
> FND-333 - Eliminate remaining circular definitions and naming related hygiene issues in FND

- IND/EconomicIndicators/EconomicIndicators.rdf
Added a synonym of 'basket of goods' to 'fixed basket'; renamed 'GoodsOrServicesPopulation' to 'FixedBasketPopulation' accordingly, but added a synonym of 'goods and services population' to make it parallel with the basket naming and for clarity, correcting a hygiene issue as well as reflecting the synonym on fixed basket, per the FCT
Fixes: #1376 / IND-103
> IND-103 - Need a synonym of 'basket of goods' on fixed basket and address hygiene issue for the name of GoodsOrServicesPopulation

- SEC/Debt/Bonds.rdf
- SEC/Debt/DebtInstruments.rdf
Eliminated explicit call price and put price from debt instruments, which were misleading terms and typically used in conjunction with options rather than with bonds, and replaced them with monetary price where they were originally used
Fixes: #1014 / SEC-140
> SEC-140 - CallPrice and PutPrice in DebtInstruments need review

- IND/EconomicIndicators/NorthAmericanIndicators/CAEconomicIndicators.rdf
- IND/ForeignExchange/ForeignExchange.rdf
Corrected wrong datatype in the Canadian Economic Indicators ontology (was on a note), and removed extraneous references from ForeignExchange, one of which was not a true URL but typed as anyURI
Fixes: #1416 / IND-105
> IND-105 - Explanatory note in CA Economic Indicators has wrong datatype

- SEC/Equities/EquitiesExampleIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
Changed the name of equity issuer to share issuer for clarification purposes per the SEC FCT.  Some organizations such as LLCs also issue equity, but not shares per se, so we should rename equity issuer to share issuer to be clear about the role it plays.
Fixes: #1418 / SEC-151
> SEC-155 - Equity issuer should be renamed to share issuer, just to be clear

- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/Forwards.rdf
- DER/DerivativesContracts/Options.rdf
Moved a number of properties that seemed common to multiple kinds of derivatives from the provisional forwards ontology to derivatives basics, including hasContractSize, has first and last delivery date, and has first and last notice date (which are related to settlement specifically) in advance of releasing the Forwards ontology.
Fixes: #1420 / DER-93
> DER-93 - Move a number of more general properties from Forwards to either Derivatives Basics or to Securities

- SEC/MetadataSEC.rdf
revised metadata for the SEC domain to properly in……corporate metadata for the funds module
Revised metadata for the SEC domain to properly incorporate metadata for the funds module
Fixes: #1425 / SEC-152
> SEC-152 - Orphaned SEC Funds Module

- AboutFIBODev.rdf
- AboutFIBOProd.rdf
- DER/AllDER.rdf
- DER/CommoditiesDerivatives/CommoditiesContracts.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
- DER/DerivativesContracts/MetadataDERDerivativesContracts.rdf
- DER/FxDerivatives/FxContracts.rdf
- DER/FxDerivatives/FxOptions.rdf
- DER/SecurityBasedDerivatives/EquityForwards.rdf
- catalog-v001.xml
Renamed Forwards to FuturesAndForwards, revised metadata and a couple of definitions per FCT discussion and released the Futures and Forwards ontology
Fixes: #1432 / DER-96
> DER-96  - Rename the Forwards ontology to Futures and Forwards, and release it

- IND/InterestRates/CommonInterestRates.rdf
Revise the FpML reference interest rates to reflect the latest version, published on 2/19/2021 based on individuals published at http://www.fpml.org/coding-scheme/floating-rate-index-2-32.xml and converted to RDF by Pete Rivett
Fixes: #1430 / IND-106
> IND-106 - Update the FpML reference interest rates per the latest published version

- FBC/FinancialInstruments/InstrumentPricing.rdf
Added a property for hasRoundLotSize, with a synonym of 'has unit of trading' and 'normal trading unit' to Instrument Pricing, as a subproperty of hasLotSize, for use in derivatives valuation and pricing
Fixes: #1434 / DER-94
> DER-94 - Add 'has round lot size' as a subproperty of hasLotSize, and 'has unit of trading' as a synonym

- FBC/FinancialInstruments/FinancialInstruments.rdf
Revised the definition of financial instrument to remove the words 'or equity instrument', per SEC FCT discussion
Fixes: #1438 / FBC-273
> FBC-273 - Eliminate unnecessary text from the definition of financial instrument

- FBC/DebtAndEquities/Debt.rdf
- FBC/DebtAndEquities/Guaranty.rdf
- LOAN/LoanTypes/CreditProducts.rdf
- LOAN/LoanTypes/MortgageLoans.rdf
Augmented the definition of collateral to include physical and non-physical collateral, cleaned up the definition of letter of credit, which might or might not be collateral depending on the circumstances, and leveraged the definition of physical collateral in loans where appropriate.
Fixes: #1441 / FBC-205
> FBC-205 - Collateral should be further refined

- FND/AgentsAndPeople/People.rdf
Added 3 properties to the People ontology, hasResidence, hasPrimaryResidence, and hasMailingAddress, and revised the restriction on person that used hasAddress to be hasResidence (still min 0)
Fixes: #1444 / FND-337
> FND-337 - Need to be able to identify a person's place of residence

- SEC/Debt/Bonds.rdf
Distinguished zero coupon from original issue discount bonds, per SEC FCT discussion; renamed terms that are the same for both OID and zero coupon bonds 'accrual bond' terms
Fixes: #1446 / SEC-153
> SEC-153 - Contract terms for zero coupon bonds are conflated with original issue discount bonds

- FND/Parties/Parties.rdf
Revised the hasRelatedPartyInRole property in the parties ontology to be symmetric
Fixes: #1448 / FND-336
> FND-336 - hasRelatedPartyInRole should be symmetric

- etc/testing/hygiene/testHygiene0004.sparql
- etc/testing/hygiene/testHygiene0268.sparql
- etc/testing/hygiene/testHygiene1068.sparql
- etc/testing/hygiene/testHygiene1078.sparql
- etc/testing/hygiene/testHygiene1079.sparql
- etc/testing/hygiene/testHygiene1103.sparql
- etc/testing/hygiene/testHygiene1198_dev.sparql
- etc/testing/hygiene/testHygiene1292.sparql
This PR increases all hygiene test at the WARN level to the PRODERROR level.
Fixes: #1451
> All hygiene tests not lower than PRODERROR level

- IND/EconomicIndicators/EconomicIndicators.rdf
Per IND FCT discussion, modified the representation of a fixed basket to be a dated collection, which means that the dates are on the elements of the basket rather than the basket as a whole, similar to the representation of indices such as the DJIA; also revised the restriction on CPI to use a fixed basket rather than generic basket
Fixes: #1453 / IND-104
> IND-104 - A fixed basket should not be fixed for a period of time

- FND/AgentsAndPeople/People.rdf
- FND/Parties/Parties.rdf
Moved hasMailingAddress from People to Parties and changed it's domain to independent party to support both business mailing addresses and personal mailing addresses
Fixes: #1462 / FND-338
> FND-338 - The domain of hasMailingAddress should be IndependentParty rather than Person

- IND/MarketIndices/BasketIndices.rdf
Added the concept of market capitalization and linked it to capitalization-based weighting function, which was a gap identified by the IND FCT
Fixes: #1465 / IND-102
> IND-102 - Missing expression for calculating market cap

- BE/GovernmentEntities/NorthAmericanJurisdiction/USGovernmentEntitiesAndJurisdictions.rdf
- BE/LegalEntities/NorthAmericanEntities/USExampleEntities.rdf
- DER/DerivativesContracts/SwapsIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USMarketsAndExchangesIndividuals.rdf
- IND/InterestRates/MarketDataProviders.rdf
Replaced all references to the legacy LCC representation for the United States with United States of America; other countries for which there are multiple names had already been updated in FIBO
Fixes: #1467 / BE-236
> BE-236 - Elements and jurisdictions should point to the current UN name for countries

- BE/Corporations/Corporations.rdf
- BE/LegalEntities/NorthAmericanEntities/USExampleEntities.rdf
- BE/OwnershipAndControl/Executives.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf
- FBC/ProductsAndServices/ClientsAndAccounts.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- SEC/Equities/EquityInstruments.rdf
Made hasNominalCapital a subproperty of hasMonetaryAmount and cleaned up the explanatory note.  Also made  incorporation and registration dates explicit dates rather than simple dates.
Fixes: #1471 / BE-233
> BE-233 - hasNominalCapital should be a subproperty of hasMonetaryAmount in Corporations

- FBC/FinancialInstruments/FinancialInstruments.rdf
- SEC/Debt/DebtInstruments.rdf
Added 3 min 0 restrictions on debt instrument in FBC, including hasDurationToMaturity, hasTimeToMaturity and hasMaturityDate, which were missing, and eliminated the now redundant hasTimeToMaturity date from SEC on debt instrument which required a maturity date (was someValuesFrom).
Fixes: #1473 / SEC-90
> SEC-90 - Certain rare debt instruments have no maturity date (e.g., consol) and so the restriction on time to maturity is too narrow

- SEC/Securities/SecuritiesClassification.rdf
Removed declarations that said a CFI code is both a classifier and a code, since codes apply to exactly 1 thing, causing all instruments that have that code to be inferred to be equivalent to one another.  Note that fixing this improved reasoning time significantly (from 28.5 hours to 27.3 hours, including all example and reference individuals over all of SEC and its imports).
Fixes: #1475 / SEC-155
> SEC-155 - Address equivalence issue related to common shares

- FBC/FinancialInstruments/InstrumentPricing.rdf
Changed both mean price determination and closing price determination method to be named individuals rather than classes and corrected a bug on mean price determination that said it was a subclass of price determination method rather than a type per FCT discussion
Fixes: #1477 / FBC-280
> FBC-280 - MeanPriceDetermination defined as a named individual - not as a class

- FND/Parties/Parties.rdf
Augmented the Parties ontology with two additional property chains that complete the 'long way around' the lattice for use in AML and other use cases
Fixes: #1479 / FND-341
> FND-341 - Complete the situational lattice for the 'long way around' the pattern

- FND/Agreements/Contracts.rdf
Cleaned up the definition of transferable contract and made it a direct subclass of written contract, including elimination of an unnecessary equivalence; added subclasses for assignable and novateable contracts; moved restrictions from contract to written contract that did not make sense with respect to a verbal contract, and moved restrictions from transferable contract to written contract that made sense for written contracts in general
Fixes: #1481 / FND-334
> FND-334 - Simplify the definition of transferable contract by making it a direct subclass of written contract

- FBC/ProductsAndServices/ClientsAndAccounts.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- FND/OwnershipAndControl/Ownership.rdf
- SEC/Equities/EquityInstruments.rdf
This resolution involved renaming certain ownership properties to better align with the situational pattern, to improve consistency and clarify usage, including: 
(1) hasOwnedThing --> hasOwnedAsset (name was inconsistent with target range), 
(2) isOwnedThingInRole --> isOwnedAsset (inverse of hasOwnedAsset), 
(3) isOwningPartyInRole --> isOwningParty (name was inconsistent with its inverse), 
(4) isOwnedBy --> isAssetOf (for consistency with the pattern - points from asset to owner), 
(5) added ownsAsset - inverse of isAssetOf (party in role to party in role, was a gap), 
(6) made owns a subproperty of 'plays active role that directly affects', and 
(7) added a new isOwnedBy, subproperty of experiences directly and inverse of owns to …
> FND-342 - Revise the ownership lattice relations to better align with the situational model

- FBC/FinancialInstruments/InstrumentPricing.rdf
Reversed a change that made closing price determination method a named individual rather than a class due to how it is used, and the fact that there may be multiple, distinct methods for determining closing prices depending on the exchange, institution, etc.
Fixes: #1492 / FBC-280
> FBC-280 - A recent change involving price determination methods inadvertently introduced punning

- IND/EconomicIndicators/EconomicIndicators.rdf
- IND/Indicators/Indicators.rdf
- IND/MarketIndices/BasketIndices.rdf
- IND/MarketIndices/EquityIndexExampleIndividuals.rdf
Eliminated restrictions on reference rate and economic indicator for the value of the corresponding rate or index; added a restriction for isValueOf on the market rate to point to the thing it is a value of; made reference rate a subclass of scoped measure; eliminated the subclass on published financial information from market rate.
Fixes: #1496 / IND-91
> IND-91 - Eliminate unnecessary properties that are currently on an index

- FBC/ProductsAndServices/CardAccounts.rdf
Revised subclass relationship in card accounts to make a cardholder a subclass of customer account holder rather than of a "vanilla" account holder
Fixes: #1505 / FBC-279
> FBC-279 - Cardholder should be a subclass of CustomerAccountHolder

- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
Added a restriction to primary federal regulator explicitly stating that such a regulator has identity exactly 1 government body
Fixes: #1507
> FBC-282 - Need a restriction on PrimaryFederalRegulator indicating that it hasIdentity a government body

- BE/OwnershipAndControl/OwnershipParties.rdf
Added a restriction on Entity Ownership indicating that it may have a value for ownership percentage
Fixes: #1509 / BE-241
> BE-241 - Need a restriction on entity ownership indicating the percentage

- IND/Indicators/Indicators.rdf
- IND/MarketIndices/EquityIndexExampleIndividuals.rdf
Revised the definition of market rate to read 'rate that represents a ratio value established in the marketplace for' ... per FCT discussion
Fixes: #1515 / IND-107
> IND-107 - The definition of 'market rate' should not incorporate the concept of a market trend

- SEC/Funds/Funds.rdf
Modified classification of legal fund structure to be a subclass of rather than equivalent to the union of legal entity and fund contract to eliminate a reasoning error and added a restriction for jurisdiction per the definition
Fixes: #1518 / SEC-158
> SEC-158 - LegalFundStructure should be a subclass rather than equivalent to LegalEntity or FundContract

- FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf
This resolution revises the original change made by @oldskeptic to address a handful of issues identified during the SEC/FBC review process.  We revised the representation of certain Canadian tax identifiers to identify rather than be ledger accounts, and added missing prefixes, eliminated redundant subclass relations.
Fixes: #1504
> FBC-#1504 - Add Canadian Business Numbers and Tax Accounts

- FND/Utilities/Analytics.rdf
Revised the URI on ratio to reflect the redirect and link to the proper section of the Statistics Canada site
Fixes: #1528
> #1528 - Problem with RATIO

- FBC/FunctionalEntities/Markets.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf
Modified the markets ontology to loosen constraints on the location in which a given exchange operates, given that there are cases when an exchange may operate in multiple locations, and to allow an exchange name to be multilingual or expressed in a language other than English
Fixes: #1532 / FBC-281
> FBC-281 - The restriction on exchange that says it operates in exactly 1 municipality is too narrow

- SEC/Funds/CollectiveInvestmentVehicles.rdf
Added key investor information document per discussion during the SEC FCT discussion on 6/7/2021; eliminated the subproperty relationship causing a reasoning error on the CIV class as identified in the issue, and cleaned up some additional redundancy in the provisional CIV ontology also identified during the FCT discussion
Fixes: #1524 / SEC-159
> SEC-159 - Class https://spec.edmcouncil.org/fibo/ontology/SEC/Funds/Funds/CollectiveInvestmentVehicle is unsatisfiable

- DER/AllDER.rdf
- DER/CommoditiesDerivatives/CommoditiesContracts.rdf
- DER/DerivativesContracts/CurrencyContracts.rdf
- DER/DerivativesContracts/ExoticOptions.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
- DER/DerivativesContracts/Options.rdf
- DER/SecurityBasedDerivatives/EquityOptions.rdf
- FBC/FunctionalEntities/Markets.rdf
- SEC/Debt/Bonds.rdf
This resolution includes additional clean-up of the options ontology and content related to it.  We have (1) eliminated the concepts related to novated contract, which will be generalized in FND, (2) eliminated the references to exercise conventions from bonds, (3) added a property and direct reference to exercise style in options, (4) eliminated an unused import in FuturesAndForwards and updated the DER all file to address a missing reference, (5) added the concept of an exchange participant in the markets ontology and used that instead of  'options exchange participant' in options, and (6) revised the intersection of exchange participant and option issuer with a union, all in preparation for releasing the options ontology (which is very close).
Fixes: #1529 / DER-99 / DER-64
> DER-99 - Complete reconciliation of exercise terms/date in Options

- BE/LegalEntities/LEIEntities.rdf
- FND/AgentsAndPeople/Agents.rdf
- FND/AgentsAndPeople/People.rdf
- FND/Relations/Relations.rdf
Simplified property declarations that used the new Text datatype to avoid issues with Protege and Pellet, but retained the concept for use in applications that support RDF 1.1 and rdf:langString.
Fixes: #1533 / FND-346
> FND-346 - Need the definition of a structured name and definition of a new datatype for the combination of xsd:string and rdf:langString

- FND/AgentsAndPeople/People.rdf
- FND/DatesAndTimes/FinancialDates.rdf
- FND/Law/Jurisdiction.rdf
- IND/EconomicIndicators/EconomicIndicators.rdf
In this resolution we (1) added the concept of age and a related property, hasAge, to FinancialDates, as age can apply to many things; (2) added concepts for age of majority, legal age, legal working age, and legal working age person to the people ontology together with relevant properties, and refined the concept of an adult to incorporate the notion of age of majority, and refined the concept of a person to have an age (optionally, in case the age is not known) in People; (3) added jurisdiction to legal age in jurisdictions, and (4) added the definition of a civilian non-institutional person to economic indicators and used that definition to define civilian non-institutional population.
Fixes: #1540 / IND-100
> IND-100 - The definition of civilian non-institutional person is not right

- AboutFIBOProd.rdf
- DER/AllDER.rdf
- DER/CommoditiesDerivatives/CommoditiesContracts.rdf
- DER/DerivativesContracts/CurrencyContracts.rdf
- DER/DerivativesContracts/ExoticOptions.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
- DER/DerivativesContracts/Options.rdf
- DER/RateDerivatives/IROptions.rdf
- DER/SecurityBasedDerivatives/EquityOptions.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- SEC/Securities/SecuritiesListings.rdf
In preparation for releasing the options ontology, we (1) added TradingStrategy to the financial products and services ontology, (2) moved exotic option back from the exotic options ontology to the main options ontology to fill out the taxonomy, (3) renamed 'combination option' to 'option trading strategy' and made it a subclass of the new trading strategy class, (4) made option on future a subclass of vanilla option, and (5) eliminated several unused classes - option guarantor, standardized exercise terms, traded option principal, traded options counterparty, underlying asset buyer and underlying asset seller.
We have also revised the prefix of the ontology from fibo-der-der-opt to fibo-der-drc-opt so that it corresponds to the other …
> DER-101 - Finalize the Options ontology for release

- SEC/Equities/EquityInstruments.rdf
Moved properties / restrictions that define how many shares have been issued/outstanding/treasury/floating from the issuer to the share
Fixes: #1544 / SEC-157
> SEC-157 - For a given equity instrument, we are missing the number of shares issued of a given class of share

- etc/testing/hygiene/testHygiene1292.sparql
This replaces 'warning' with 'error' in hygiene test 1292.
Fixes: #1548
> Fix to hygiene test 1292

- CONTRIBUTING.md
This adds missing links to CONTRIBUTING.md.
Fixes: #1216
> Missing links in CONTRIBUTING.md added

- FND/Agreements/Contracts.rdf
Changed a skos:definition that was tagged as a second definition on hasContractDuration, that should have been a note from the outset, to a FIBO explanatory note
Fixes: #1553 / FND-348
> FND-348 - fibo-fnd-agr-ctr:hasContractDuration has 2 skos:definition triplets

- FBC/FinancialInstruments/FinancialInstruments.rdf
Revised the definition of hasTimeToMaturity to clarify its meaning to that of term to maturity and added the synonym; added a new data property, hasDaysToMaturity, to enable banks and other institutions to track the residual maturity of the instruments on their books
Fixes: #1555 / SEC-154
> SEC-154 - Need to review the notion of time to maturity

- AboutFIBOProd.rdf
- DER/AllDER.rdf
- DER/DerivativesContracts/CurrencyContracts.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
Revised CurrencyFuture to eliminate redundant subclass and restriction axioms given that CurrencyContracts adds more appropriate restrictions; added the relationship with CurrencyFutures in CurrencyContracts; released CurrencyContracts
Fixes: #1559 / DER-103
> DER-103 - Clean up and release the currency contracts ontology

- DER/DerivativesContracts/FuturesAndForwards.rdf
- SEC/Equities/EquityInstruments.rdf
- SEC/Funds/CollectiveInvestmentVehicles.rdf
The resolution to this issue clarifies the definition of dividend to explicitly state that it reflects the announced commitment to pay a dividend rather than being something like a more general policy to do so.  We also cleaned up the definition of DividendFuture to point to the equity rather than the specific dividend, and eliminated redundancy related to dividends in the CIV ontology.
Fixes: #1561 / SEC-135
> SEC-135 - Unclear how Dividend class is meant to be used

- BP/SecuritiesIssuance/AgencyMBSIssuance.rdf
- MD/DebtTemporal/DebtPricingYields.rdf
- SEC/Debt/AssetBackedSecurities/AssetBackedSecurities.rdf
- SEC/Debt/AssetBackedSecurities/CDOs.rdf
- SEC/Debt/AssetBackedSecurities/CMOs.rdf
- SEC/Debt/AssetBackedSecurities/MortgageBackedSecurities.rdf
- SEC/Debt/AssetBackedSecurities/PoolBackedSecurities.rdf
Preliminary restructuring of asset-backed securities and some renaming to replace abbrevations with full names based on discussion in the SEC FCT
Fixes: #1570 / SEC-163
> SEC-163 - Restructure ABS such that a cash structured finance instrument is a subclass of debt instrument rather than bond

- AboutFIBOProd.rdf
- DER/AllDER.rdf
- DER/DerivativesContracts/CommoditiesContracts.rdf
- IND/MarketIndices/BasketIndices.rdf
Revised several definitions based on discussion in the DER FCT on 17 Aug 2021, including (1) the definition of BaseIndustrialMetal, which we renamed BaseMetal, (2) the definition of commodity option, which we aligned with the CFI standard, and (3) the more general definition of Metal.  Other changes include (4) the addition of WeatherDerivative, (5) addition of BasketOfCommodities and CommodityBasketConstituent - consisting of negotiable commodities, in support of the references to such baskets in the CFI standard, and (6) relaxation of a restriction on reference index to allow it to reflect any sort of weighted basket, thus enabling us to represent commodity indices.
Fixes: #1572 / DER-105
> DER-105 - Definitions in the commodities ontology need additional work in preparation for release

- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- FND/Arrangements/Arrangements.rdf
- IND/MarketIndices/EquityIndexExampleIndividuals.rdf
Added a restriction to structured collection pointing to the arrangement used to organize that collection, and to revise the definition accordingly, and then used the new properties to better describe the S&P 500 and DJIA
Fixes: #1574 / IND-109
> IND-109 - Need to revise the definition of S&P 500

- SEC/Debt/TradedShortTermDebt.rdf
Clarified the definition of a bill of exchange, including (1) moving it up the hierarchy to a subclass of tradable debt instrument, adding an explanatory note and a synonym of 'bank draft', and (2) revising the definition of bankers' acceptance to say that it is both a bill of exchange and a fixed income security, which a bill of exchange may or may not be
Fixes: #1582 / SEC-68
> SEC-68 - The definition of bill of exchange needs clarification

- DER/SecurityBasedDerivatives/EquityForwards.rdf
Revised the class name from EquityForwardContract to EquityForward per our naming conventions, modified the underlier for equity forward to include equity futures and options, and added a definition from the CFI standard which was missing
Fixes: #1589 / DER-110
> DER-110 - Equity forwards need to have a broader underlier than what is available in a typical equity derivative

- DER/DerivativesContracts/Options.rdf
- SEC/Debt/ExerciseConventions.rdf
Added an expiration date to all options (which was a gap) and eliminated the restriction with respect to an exercise window on American exercise terms given that we have the expiration date.
Fixes: #1597 / DER-98
> DER-98 - The definition of American Exercise Terms should involve an exercise by date rather than a window

- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
Addressed issue with a restriction on state government entity
Fixes: #1617 / FBC-291
> FBC-291 - FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies/ fibo-fbc-fct-usjrga:StateGovernmentEntity has invalid restriction

- DER/DerivativesContracts/Options.rdf
Corrected restriction on Option involving an optional calculated market value that was not well-formed
Fixes: #1618 / DER-115
> DER-115 - DER/DerivativesContracts/Options/ fibo-fbc-fi-fi:Option has an invalid restriction

- etc/testing/hygiene/testHygiene1610.sparql
This PR refactors the test for deprecated resources so that only in-use deprecated ones are reported.
For the time being it is a warning test.
Fixes: #1610
> Hygiene test for deprecated resources refactored

- IND/MarketIndices/BasketIndices.rdf
Remedied an illegal property chain (replacing it with an existing non-chained property) in the definition of market capitalization
Fixes: #1619 / IND-112
> IND-112 - FND/MarketIndices/BasketIndices/hasSharesOutstandingForIssuer is assigned to an invalid property chain

- etc/testing/hygiene/testHygiene1624.sparql
- etc/testing/hygiene/testHygiene1624_chain.sparql
- etc/testing/hygiene/testHygiene1624_disjoint.sparql
- etc/testing/hygiene/testHygiene1624_equivalent.sparql
- etc/testing/hygiene/testHygiene1624_inverse.sparql
- etc/testing/hygiene/testHygiene1624_subProperty.sparql
This PR adds a couple of hygiene tests to detect illegal punning for object and datatype properties.
Fixes: #1624 (and refers back to #1619)
> Hygiene test for object/datatype properties punning

- DER/DerivativesContracts/RightsAndWarrants.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- SEC/Debt/ExerciseConventions.rdf
- SEC/Securities/SecuritiesIssuance.rdf
Initial pass to clean up the rights and warrants ontology for release, including (1) enabling exercise terms to apply to entitlements, (2) revising the class hierarchy for financial instruments to include entitlements under securities, (3) clean up the definition of security form to make it clearer and not circular, and (4) a number of revisions to rights and warrants to add CFI definitions where appropriate, eliminate duplication, and adjust the hierarchy based on the fact that most entitlements apply to more than simply equities
Fixes: #1615 / DER-114
> DER-114 - Clean up the Rights and Warrants ontology in preparation for release

- DER/DerivativesContracts/RightsAndWarrants.rdf
Eliminated punning (erroneous superproperty) on hasConversionRatio in Rights and Warrants
Fixes: #1628
> DER-1628 - Illegal punning for hasConversionRatio

- etc/testing/hygiene/testHygiene0002.sparql
- etc/testing/hygiene/testHygiene0003.sparql
- etc/testing/hygiene/testHygiene0005.sparql
- etc/testing/hygiene/testHygiene0268.sparql
- etc/testing/hygiene/testHygiene1067.sparql
- etc/testing/hygiene/testHygiene1624.sparql
- etc/testing/hygiene/testHygiene1624_chain.sparql
- etc/testing/hygiene/testHygiene1624_disjoint.sparql
- etc/testing/hygiene/testHygiene1624_equivalent.sparql
- etc/testing/hygiene/testHygiene1624_inverse.sparql
- etc/testing/hygiene/testHygiene1624_subProperty.sparql
This cleans up prefixes in hygiene tests by:
- adding the required ones
- removing the unused ones
Fixes: #1626
> Prefixes in hygiene tests were refactored

- DER/DerivativesContracts/Options.rdf
Modified the definition of interest rate option to reflect a benchmark, and to be a specialization of vanilla option
Fixes: #1640 / DER-118
> DER-118 - The definition of interest rate option refers to a flat rate and should refer to a benchmark

- FND/Arrangements/Assessments.rdf
- LOAN/LoanContracts/LoanCore.rdf
- LOAN/LoanTypes/MortgageLoans.rdf
In loan contracts, cleaned up and generalized a number of definitions, including collateralized loan, combined and loan-to-value ratio, fee-simple and fractional ownership interest (and related ownership interest to ownership, which it classifies), added definitions for primary and subordinate lien position, and generalized a number of property definitions; In assessments, added the concept of appraised value and properties related to estimated value of an asset to the definition of appraisal
Fixes: #1643 / LOAN-152
> LOAN-152 - Further refine the definitions in LoanCore

- FND/Arrangements/Assessments.rdf
Replaced the superproperty of hasAppraiser with isProvidedBy to correct a punning issue
Fixes: #1653 / FND-356
> FND-356 - Bug in the Assessments ontology in the definition of hasAppraiser

- IND/InterestRates/CommonInterestRates.rdf
Revised the common interest rates reference data ontology to reflect the latest 2021 FpML rates, which include a number of changes, deprecating some rates and replacing them with others; also revised how some rates are represented, eliminating duplication where feasible in cases where multiple publishers make exactly the same rate available - users can add the source from which they reference the rate in those cases where it is important for valuation / documentation purposes
Fixes: #1655 / IND-114
> IND-114 - Generate the latest FpML interest rates as reference data in the Common Interest Rates ontology

- FND/Accounting/AccountingEquity.rdf
- SEC/Securities/Pools.rdf
Deprecated the property representsAnInterestIn, which was confusing and used in different ways across the couple of ontologies that used it; it was actually redundant and in one place incorrect when used in the Pools ontology and the term PoolEquity, which was not well defined and not used anywhere was also deprecated
Fixes: #1659
> FND-353 - Concepts in Accounting Equity need to be reconciled with the Ownership pattern

- FND/OwnershipAndControl/OwnershipAndControl.rdf
Modified properties ownsAndControls and isOwnedAndControlledBy to be subproperties of the corresponding properties in ownership and control to connect them to the patterns for improved analysis
Fixes: #1661 / FND-357
> FND-357 - Properties in the OwnershipAndControl ontology are not linked to the situational pattern

- FND/Law/LegalCapacity.rdf
- FND/ProductsAndServices/ProductsAndServices.rdf
This resolution introduces 'right' as a kind of legal construct, move legal right, contractual right, and contingent right under right as siblings, and updates their definitions appropriately.  It also incorporates the concept of a right into the definition of product, to cover leases and rentals, such as the right to use a piece of property or other asset for some period of time, as products.
Fixes: #1665 / FND-313
> FND-313 - The definitions related to rights under legal construct are unclear and need refactoring

- FBC/DebtAndEquities/Debt.rdf
Fixed erroneous prefix that crept in during a change to the Debt ontology
Fixes: #1680 / DER-120
> DER-120 - correct hygiene issue

- FND/Accounting/ISO4217-CurrencyCodes.rdf
- etc/testing/hygiene/testHygiene0114.sparql
Reflects ISO codes published Oct 2021, and reconciles with latest LCC 1.2 - specifically change to North Macedonia.
Adds explanation for transitional code VED in Venezuela based on official ISO notice.
Fixes: BE-244
- [x ] My contribution follows the [principles of best practices for FIBO](https://github.com/edmcouncil/fibo/blob/master/ONTOLOGY_GUIDE.md).
- [x ] The issue has been tested locally using a reasoner (for ontology changes).
> Use latest ISO and LCC files, hand edits for VED

- FND/Accounting/CurrencyAmount.rdf
Revise the definition of currency to eliminate an inconsistency caused by multiple numeric codes for the Venezuelan currency present in the October 2021 update to the ISO 4217 currency codes
Fixes: #1686 / FND-358
> FND-358 - Revisions to the currency codes caused a logical inconsistency

- BE/GovernmentEntities/EuropeanJurisdiction/SouthernEuropeGovernmentEntitiesAndJurisdictions.rdf
Revised the definitions for government entities related to North Macedonia to reference the updated LCC ISO 3166 country definition for NorthMacedonia
Revised the definitions for government entities related to North Macedonia to reference the updated LCC ISO 3166 country definition for NorthMacedonia
Fixes: #1669 / BE-244
> BE-244 - References to Macedonia in BE (and in currencies in FND) should be revised to reference NorthMacedonia instead

- SEC/Debt/MetadataSECDebt.rdf
corrected time stamp for the Q1 2022 quarterly release in ……SEC/Debt metadata
Corrected time stamp for the Q1 2022 quarterly release in SEC/Debt metadata
Fixes: #1684
> SEC-1684 - Wrong dateTime in MetadataSECDebt

- catalog-v001.xml
This fixes the wrong references to files in catalog-v001.xml
Fixes: #1695
> Wrong references in catalog-v001.xml fixed

- FND/Places/Facilities.rdf
Allow a facility to have an address without requiring it to be situated at some site to simplify usage in cases where the site and facility have 100 percent overlap
Fixes: #1693 / FND-360
> FND-360 - Facilities may not be associated with a site and need an address

- AboutFIBOProd.rdf
- SEC/AllSEC.rdf
- SEC/Debt/PoolBackedSecurities.rdf
The SEC FCT determined based on review of the pool-backed securities ontology that the work raised in this issue had been accomplished under SEC-170 in a prior pull request, and that the remaining work was simply to release the ontology.  This resolution revises the metadata in the ontology to bring it to released status and adds it to the SEC 'all' make file and to the AboutFIBOProd make file accordingly.
Fixes: #1670 / SEC-170
> SEC-170 - Further work is needed to clean up the pool-backed securities ontology

- SEC/Equities/EquityInstruments.rdf
Simplified the representation of voting rights per share, deprecating complex individuals that caused issues for some tools
Fixes: #1698 / SEC-173
> SEC-173 - Instances of owl:Restriction

- etc/testing/hygiene/testHygiene1610.sparql
- etc/testing/hygiene/testHygiene1675_classes.sparql
- etc/testing/hygiene/testHygiene1675_datatypeproperties.sparql
- etc/testing/hygiene/testHygiene1675_deprecated_resources.sparql
- etc/testing/hygiene/testHygiene1675_individuals.sparql
- etc/testing/hygiene/testHygiene1675_objectproperties.sparql
This PR modifies the test for deprecated resources so that deprecated individuals are not reported.
It also added a number of INFO-level tests that count number of individuals, classes, and properties.
Fixes: #1675
> Tests for deprecated resources were modified

- SEC/Equities/EquityCFIClassificationIndividuals.rdf
Simplified individual common shares with respect to their individual instrument classifiers by eliminating unnecessary restrictions
Fixes: #1704 / SEC-169
> SEC-169 - Simplify the CFI codes for equity instruments to eliminate the restrictions on hasDenotation

- DER/RateDerivatives/IRSwapExampleIndividuals.rdf
- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
This resolution corrects a typo in the securities identifiers individuals ontology and two cases in the IR Swaps examples where a property in the main ontology had changed but the examples were not updated as they should have been.
Fixes: #1707 / SEC-147
> SEC-174 - Misquoted properties in PROD

- catalog-v001.xml
Added missing 'load files' to the high-level catalog
Fixes: #1695
> FIBO-1695 - Files missing in catalog-v001.xml

- SEC/Equities/DepositaryReceipts.rdf
Revised the definition of depositary receipt to broaden explanatory notes allowing for inclusion of Chinese ADRs
Fixes: #1711 / SEC-166
> SEC-166 - Need to broaden the definition of depositary receipt in order to cover other approaches

- DER/DerivativesContracts/CommoditiesContracts.rdf
- FND/Accounting/CurrencyAmount.rdf
- FND/Accounting/ISO4217-CurrencyCodes.rdf
- FND/ProductsAndServices/ProductsAndServices.rdf
Moved the definition of precious metal and precious metal identifier from products and services to currency amount
Fixes: #1716 / FND-362
> FND-362 - Remove dependency of CurrencyCodes on PAS for PreciousMetal

- etc/testing/hygiene/testHygiene0001_objects.sparql
- etc/testing/hygiene/testHygiene0001_properties.sparql
- etc/testing/hygiene/testHygiene0001_subjects.sparql
- etc/testing/hygiene/testHygiene0002.sparql
- etc/testing/hygiene/testHygiene0003.sparql
- etc/testing/hygiene/testHygiene0004.sparql
- etc/testing/hygiene/testHygiene0005.sparql
- etc/testing/hygiene/testHygiene0114.sparql
- etc/testing/hygiene/testHygiene0268.sparql
- etc/testing/hygiene/testHygiene1068.sparql
- etc/testing/hygiene/testHygiene1078.sparql
- etc/testing/hygiene/testHygiene1079.sparql
- etc/testing/hygiene/testHygiene1103.sparql
- etc/testing/hygiene/testHygiene1177.sparql
- etc/testing/hygiene/testHygiene1190.sparql
- etc/testing/hygiene/testHygiene1190_properties.sparql
- etc/testing/hygiene/testHygiene1198.sparql
- etc/testing/hygiene/testHygiene1290.sparql
- etc/testing/hygiene/testHygiene1293.sparql
- etc/testing/hygiene/testHygiene1610.sparql
This implements the change mentioned in the issue: now all hygiene tests filter out non-EDMC entities in the same way.
Fixes: #1719
> Hygiene test filter out non-EDMC resources in the same way

- etc/testing/hygiene/testHygiene1675_deprecated_resources.sparql
- etc/testing/hygiene_parameterized/testHygiene1675_deprecated_resources.sparql
This adds the missing prefix declaration to the hygiene test for deprecated resources.
Fixes: #1725
> Missing prefix declaration added to hygiene test for deprecated resources

- SEC/Debt/Bonds.rdf
Augmented the definition of TreasuryBill with an explanatory note and added that U.S. Treasury securities are issued in U.S. dollars in a restriction
Fixes: #1723
> SEC-70 - The definition of TreasuryBill in Bonds is incomplete

- BE/GovernmentEntities/EuropeanJurisdiction/EUGovernmentEntitiesAndJurisdictions.rdf
Removed several unused imports statements from EU government entities and jurisdictions
Fixes: #1728 / BE-70
> BE-242 - Eliminate unused imports from EU government entities

- FBC/DebtAndEquities/Debt.rdf
- SEC/Debt/MortgageBackedSecurities.rdf
Clarified the definition of RealEstateMortgageInvestmentConduit (REMIC) and eliminated a duplicate definition for promissory note
Fixes: #1738 / SEC-162
> SEC-162 - Need to distinguish REMICs from other CDOs and REITs

- BE/GovernmentEntities/EuropeanJurisdiction/EasternEuropeGovernmentEntitiesAndJurisdictions.rdf
This fix the typo in the label of [JurisdictionOfPoland](https://spec.edmcouncil.org/fibo/ontology/BE/GovernmentEntities/EuropeanJurisdiction/EasternEuropeGovernmentEntitiesAndJurisdictions/JurisdictionOfPoland)
Fixes: #1715
> Typo in label of JurisdictionOfPoland fixed

- AboutFIBODev.rdf
- CAE/CorporateEvents/CorporateActions.rdf
- CAE/CorporateEvents/GLEIF-CorporateActionIndividuals.rdf
- CAE/CorporateEvents/ISO15022-CorporateActionIndividuals.rdf
- CAE/CorporateEvents/MetadataCAECorporateEvents.rdf
- CAE/CorporateEvents/SecurityRelatedCorporateActions.rdf
- catalog-v001.xml
Revised the corporate actions and related ontologies and added a new ontology defining GLEIF-specific corporate actions to cover the content published by the GLEIF in the 3.1 version of their level 1 data for legal entities.  
Note that this work is a step in our process of releasing the corporate actions ontologies but these ontologies are still provisional.
Fixes: #1736 / IND-116
> IND-116 - Revise corporate actions to cover GLEIF actions

- DER/DerivativesContracts/CurrencyContracts.rdf
- DER/DerivativesContracts/Swaps.rdf
- DER/RateDerivatives/IRSwaps.rdf
- DER/SecurityBasedDerivatives/EquitySwaps.rdf
Added the concept of a rates swap and the corresponding rate-based leg to the swaps ontology and integrated it with the relevant subordinate ontologies to facilitate mapping to the CFI standard
Fixes: #1727 / DER-124
> DER-124 - Need to address gaps with respect to the CFI representation of swaps

- AboutFIBOProd.rdf
- CAE/AllCAE.rdf
- CAE/CorporateEvents/CorporateActions.rdf
This resolution includes updating the metadata in the Corporate Actions ontology to change its status to release and add a version to the version IRI, revise the hierarchy related to actions that notify stakeholders of changes in corporate legal form, adding a new AllCAE "make file" in the CAE domain, and adding the Corporate Actions ontology to the About FIBO Prod "make file".
Fixes: #1743 / IND-118
> IND-118 - Finalize the high-level corporate actions ontology for release

- etc/vocabulary/README.md
- etc/vocabulary/classes.sparql
- etc/vocabulary/properties.sparql
- etc/vocabulary/scaffolding.ttl
- etc/vocabulary/subclasses.sparql
- etc/vocabulary/subproperties.sparql
This adds the config data used by the ontology-publisher to create the vocabulary product. 
Fixes: #1735
> Vocabulary config data added to FIBO repository

- AboutFIBOProd.rdf
- catalog-v001.xml
Added a reference for the new AllCAE.rdf load file to the top-level FIBO catalog for loading FIBO in Protege via GitHub
Fixes: #1745
> Added AllCAE.rdf to the top-level catalog file

- FND/Accounting/ISO4217-CurrencyCodes.rdf
Corrected prefix for explanatory note in currency codes
Fixes: #1749
> typo in prefix for explanatoryNote in ISO currency codes

- SEC/Equities/EquityInstruments.rdf
Deprecated the notion of a securities restriction that is specific to limited partnership units (via deprecation), which no one would ever use in the way it was modeled, allowing elimination of importing the securities restrictions ontology and thus enabling the equity instruments ontology to be included in a t-box only view of the production ontologies in FIBO
Fixes: #1752 / SEC-177
> SEC-177 - Eliminate the notion of a limited partnership unit restriction in equity instruments

- FBC/ProductsAndServices/ClientsAndAccounts.rdf
- FND/ProductsAndServices/PaymentsAndSchedules.rdf
- LOAN/LoanContracts/LoanCore.rdf
- LOAN/LoanContracts/LoanHMDA.rdf
Revised clients and accounts to link a credit agreement with an account and loosen transaction-related constraints such that the notion of a transaction can be applied to credit agreements generally; revised payments and schedules to clean up the definition and augment the restrictions on payment obligation to include the payee; revised loan core to eliminate the various commitments to pay/re-pay, moving some features to a new loan-specific account concept and revise payment history and schedule to leverage transaction-specific concepts in FBC
Fixes: #1713 / LOAN-163
> LOAN-163 - Augment the concept of a payment schedule to include those elements needed for ILDR reporting

- FND/Accounting/ISO4217-CurrencyCodes.rdf
Revised currency codes to correct definitions for precious metals in the code generation process and added language tags
Fixes: #1721 / FND-365
> FND-365 - Wording for precious metals currency identifiers needs work

- FND/Accounting/AccountingEquity.rdf
Modified accounting equity to make income a subclass of monetary amount and eliminate the oblique restriction on monetary amount to simplify its representation
Fixes: #1757 / FND-364
> FND-364 - Income should be a child of monetary amount rather than have some oblique relationship with monetary amount

- FND/Accounting/AccountingEquity.rdf
- FND/ProductsAndServices/ProductsAndServices.rdf
- FND/Relations/Relations.rdf
Eliminate deprecated elements in FND that have been deprecated in FIBO for more than a quarter (thus excluding deprecations in currency amount)
Fixes: #1764 / FND-367
> FND-367 - Eliminate FND deprecated content

- FBC/FunctionalEntities/FinancialServicesEntities.rdf
- FND/Arrangements/IdentifiersAndIndices.rdf
Revised the definition of a composite identifier to (1) loosen the restriction on having at least one identifier to optionally having an identifier (as it could be a code), and (2) added two annotations for constructing and deconstructing a regular expression that states precisely how to build the composite identifier
Fixes: #1766
> DER-129 - Need the ability to model composite identifiers in FIBO

- FND/Places/MetadataFNDPlaces.rdf
Revised the URI in the metadata for Places that improperly referenced the US Postal Service Addresses Individuals ontology to correct it per the issue raised
Fixes: #1779 / FND-366
> FND-366 - Wrong URI for USPostalServiceAddressesIndividuals ontology

- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- LOAN/LoansGeneral/Loans.rdf
Revised the name of the property 'has total number of payments' to 'has anticipated number of payments' and released the LOAN/LoansGeneral/Loans ontology
Fixes: #1784 / LOAN-165
> LOAN-165 - Release the primary Loans ontology under LoansGeneral

- BE/LegalEntities/FormalBusinessOrganizations.rdf
This resolution removed the organization-specific deprecated elements from the FBO ontology that were moved to Foundations last year
Fixes: #1789 / BE-247
> BE-247 - Eliminate deprecated elements in formal business organizations

- DER/DerivativesContracts/ExoticOptions.rdf
- DER/DerivativesContracts/Options.rdf
1. Modified the ontology prefix from fibo-der-der-exo to fibo-der-drc-exo in line with the released ontologies in this module; 
2.  Added a number of exotic options, including barrier option, knock-in option, knock-out option, double barrier option, forward start option and cliquet option; 
3. Added details to the definition of Asian option and chooser option per the notes in the JIRA issue
4. Revised the definition of basket option in the main options ontology to make it an exotic option
5. Added several additional exotic options, including digital, commodore, compound, and lookback options
Fixes: #1780 / DER-122
> DER-122 - Need to add the major types of Exotic Options

- DER/DerivativesContracts/ExoticOptions.rdf
1. Augmented the definition of a barrier option with a number of properties, including those that apply specifically to knock-in, knock-out, and double barrier options
2. Augmented the definition of an Asian option with a couple of classifiers and several properties to complete coverage
Fixes: #1807 / DER-131
> DER-131 - Augment the exotic options ontology with properties for Barrier and Asian Options

- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/ExoticOptions.rdf
- DER/DerivativesContracts/Options.rdf
- DER/DerivativesContracts/Swaps.rdf
Augment the options ontology to include well-known trading strategies and integrate strategies that are currently in the exotic options ontology
Fixes: #1811 / DER-123
> DER-123 - We need to add Option Trading Strategies under Options

- FBC/FunctionalEntities/BusinessCentersIndividuals.rdf
Added owl:sameAs to Alma-ata in reference to Almaty (same location, where Alma-ata is an older name for the same place)
Fixes: #1781 / FBC-301
> FIBO-301 - fibo-fbc-fct-bci:Alma-ata should be owl:sameAs fibo-fbc-fct-bci:Almaty

- FBC/FinancialInstruments/InstrumentPricing.rdf
- IND/Indicators/Indicators.rdf
Removed redundant restrictions on CollectionOfSecurityPrices and loosened the constraint on PriceStructure saying that it had to include quoted prices only
Fixes: #1837 / SEC-131
> SEC-131 - CollectionOfSecurityPrices needs work

- BE/LegalEntities/LegalPersons.rdf
- SEC/Equities/DepositaryReceipts.rdf
- SEC/Equities/EquityInstruments.rdf
1. Added the concept of a variable interest entity (VIE) to legal entities and of a VIE share to equity instruments, required to define a Chinese DR
2. Added the concept of a generic Chinese DR without necessarily tying it to a VIE, but now those kinds of CDRs can be represented as appropriate
Fixes: #1838 / SEC-175
> SEC-175 - Augment the definition of an ADR to describe Chinese ADRs

- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
- DER/DerivativesContracts/Swaps.rdf
- FBC/DebtAndEquities/CreditEvents.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
- FBC/FinancialInstruments/Settlement.rdf
- FND/Arrangements/Assessments.rdf
- FND/GoalsAndObjectives/Objectives.rdf
- SEC/Debt/CollateralizedDebtObligations.rdf
- SEC/Debt/SyntheticCDOs.rdf
- SEC/Equities/EquityInstruments.rdf
- SEC/Funds/CollectiveInvestmentVehicles.rdf
1. Created the concept of a credit derivative in derivatives basics, added a subclass relation between credit derivative and total return swap, and made some preliminary changes to credit default swaps per FCT discussion on 10/11/2022
2. Simplified the model by eliminating the notion of a fee leg per discussion in the SEC FCT on 10/14
3. Replaced CDSCreditEvent with TriggeringEvent, eliminated the redundant notion of a reference obligation, which is the underlier, cleaned up definitions and eliminated additional duplication per discussion on 10/18 in the DER FCT
4. Moved the notion of a valuation method to assessments and integrated it with settlement, the valuation of an underlier in general, and eliminated redundancies in CDS as a …
> DER-136 - Restructure and clean up the Credit Default Swaps ontology

- DER/DerivativesContracts/ExoticOptions.rdf
Adjusted definitions of knock-in and knock-out barrier options to correct missing language
Fixes: #1854
> DER-1854 - Missing word in definition of knock-in option

- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- DER/AllDER.rdf
- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- DER/CreditDerivatives/MetadataDERCreditDerivatives.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
1. Augmented the CDS ontology to include single and multi-name CDS including subclasses of multi-name
2. Eliminated unnecessary restrictions on various concepts
3. Revised the definition of cash settlement method to address the potential for ad hoc auctions
4. Added 'dealers' to the possible pricing sources
5. Cleaned up a few lingering / dangling concepts to enable it to be released
6. Updated metadata files and released the CDS ontology for inclusion in production in the Q4 2022 release
Fixes: #1848 / DER-137
> DER-137 - Revise the CDS ontology to include concepts defined in the Fed overview and CFI standard

- etc/testing/hygiene_parameterized/testHygiene0005.sparql
- etc/testing/hygiene_parameterized/testHygiene0268.sparql
This temporarily allows for "duplicated" properties be used in hygiene tests - it is needed to move towards usage of OMG common libraries.
Fixes: #1860
> Extension to CMNS AV ontology added to hygiene tests

- DER/DerivativesContracts/ExoticOptions.rdf
Added the concept of a low exercise price option as an exotic call option with a European exercise convention
Fixes: #1873 / DER-106
> DER-106 - LEPOs (low exercise price option) are missing from the Exotic Options ontology

- AboutFIBODev.rdf
- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- BE/Partnerships/Partnerships.rdf
- BE/SoleProprietorships/SoleProprietorships.rdf
- BE/Trusts/Trusts.rdf
- MD/CIVTemporal/FundsTemporal.rdf
- MD/CIVTemporal/MetadataMDCIVTemporal.rdf
- MD/DebtTemporal/DebtAnalytics.rdf
- MD/DebtTemporal/MetadataMDDebtTemporal.rdf
- MD/DerivativesTemporal/ETOptionsTemporal.rdf
- MD/DerivativesTemporal/FuturesTemporal.rdf
- MD/DerivativesTemporal/MetadataMDDerivativesTemporal.rdf
- MD/MetadataMD.rdf
- MD/TemporalCore/MetadataMDTemporalCore.rdf
- MD/TemporalCore/SecurityCreditStatuses.rdf
- MD/TemporalCore/SecurityTradingStatuses.rdf
- MetadataFIBO.rdf
Revised all of the MD ontologies and metadata to replace specfication metadata with the Commons annotation vocabulary and eliminate technical debt in a few places
Fixes: #1886 / FND-372
> FND-372 - Replace specification metadata-related annotations with annotations from the Commons Ontology Library in the FIBO Market Data (MD) Domain

- BE/LegalEntities/LegalPersons.rdf
- BE/OwnershipAndControl/Executives.rdf
- FND/Law/LegalCapacity.rdf
- FND/Relations/Relations.rdf
Moved the property 'is conferred on' from relations to legal capacity where it is used, and deprecated it in relations such that circular dependencies between relations and agents can be avoided in planned updates using Commons
Fixes: #1895 / FND-374
> FND-374 - Move the property isConferredOn from Relations to LegalCapacity

- AboutFIBODev.rdf
- BE/MetadataBE.rdf
- BP/MetadataBP.rdf
- CAE/MetadataCAE.rdf
- FND/Arrangements/MetadataFNDArrangements.rdf
- FND/MetadataFND.rdf
- IND/MetadataIND.rdf
- LOAN/LoansSpecific/MetadataLOANLoansSpecific.rdf
- LOAN/RealEstateLoans/MetadataLOANRealEstateLoans.rdf
- MD/CIVTemporal/MetadataMDCIVTemporal.rdf
- MD/DebtTemporal/MetadataMDDebtTemporal.rdf
- MD/DerivativesTemporal/MetadataMDDerivativesTemporal.rdf
- MD/MetadataMD.rdf
- MD/TemporalCore/MetadataMDTemporalCore.rdf
1. added the US NIC draft controlled vocabularies ontology to FIBO Dev
2. aligned other FIBO module and domain labels for consistency in the FIBO viewer
Fixes: #1907 / FND-378
> FND-378 - Normalize metadata for display in the FIBO viewer

- FBC/FunctionalEntities/NorthAmericanEntities/USNationalInformationCenterControlledVocabularies.rdf
This resolution augmented the number and nature of institutions with NIC entity type codes. Note that there are still a handful of codes that have not been mapped, mainly due to the need for more definitive definitions for those entity types.
Fixes: #1909 / FBC-306
> FBC-306 - Augment the mapping of US NIC repository codes to entity types to cover more of those defined in FBC

- DER/DerivativesContracts/StructuredInstruments.rdf
The resolution to this issue augments the new structured instruments ontology with additional capital protected certificates (CFI clause 6.4.7) and other participation certificates that are not capital protected (CFI clause 6.4.8).
Fixes: #1914 / DER-142
> DER-142 - Additional coverage of structured instruments is needed

- SEC/Debt/AssetBackedSecurities.rdf
- SEC/Debt/CollateralizedDebtObligations.rdf
1. Cleaned up ABS with respect to bonds that were already defined in the bonds ontology
2. Added controlled amortization ABS
3. Added fully amortizing ABS
4. Moved bond pool from CDOs to ABS
Fixes: #1918 / SEC-164
> SEC-164 - Further revisions to the AssetBackedSecurities ontology are needed

- FND/Utilities/Analytics.rdf
- MD/DebtTemporal/DebtAnalytics.rdf
- SEC/Debt/MortgageBackedSecurities.rdf
- SEC/Debt/PoolBackedSecurities.rdf
1. Added a synonym of 'average' to 'arithmetic mean'
2. Moved a number of pool-specific analytical statistics from the provisional debt analytics ontology to the pool-backed securities ontology, including but not limited to: absolute prepayment rate, default rate, weighted average loan age, weighted average remaining maturity, prepayment speed, and weighted average coupon
3. Added single monthly mortality to the set of possible statistics since it was mentioned
Fixes: #1921 / SEC-184
> SEC-184 - Add common pooled securities statistics

- DER/RateDerivatives/IRSwaps.rdf
- IND/InterestRates/InterestRates.rdf
- SEC/Equities/EquityInstruments.rdf
Clarified the meaning of several restrictions and addressed an error in a restriction on specific provider interest rate benchmark
Fixes: #1899
> GIT-1889 - Use of owl:qualifiedCardinality "0"^^xsd:nonNegativeInteger

- AboutFIBODev.rdf
- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- FBC/ProductsAndServices/MetadataFBCProductsAndServices.rdf
- LOAN/AllLOAN.rdf
- LOAN/LoansSpecific/CardAccounts.rdf
- LOAN/LoansSpecific/MetadataLOANLoansSpecific.rdf
- catalog-v001.xml
1. Moved the credit cards ontology to loans specific and revised related metadata as a precursor to releasing additional ABS-related ontologies
2. Revised top level FIBO load files to include the card accounts ontology
Fixes: #1924 / FBC-311
> FBC-311 - Move the provisional credit cards ontology to loans and release it

- SEC/Securities/SecuritiesIssuance.rdf
- SEC/Securities/SecuritiesListings.rdf
Normalized the representation of security form for ease of recognition and use
Fixes: #1944 / SEC-186
> SEC-186 - Add Bearer and Bearer/Registered to Security Form

- BE/GovernmentEntities/AsianJurisdiction/WesternAsiaGovernmentEntitiesAndJurisdictions.rdf
There was a reference to lcc-3166-1:Syria which was changed to lcc-3166-1:SyrianArabRepublic.
Fixes: #1949
> issue-1949 - change resource name from Syria to SyrianArabRepublic

- DER/DerivativesContracts/RightsAndWarrants.rdf
Added classes for mini-future certificate and constant leverage option to rights and warrants, including 4 subclasses to mini-future per the CFI standard
Fixes: #1946 / DER-117
> DER-117 - The Rights and Warrants ontology is missing the concept of a mini-future certificate

- SEC/Debt/AssetBackedSecurities.rdf
Eliminated the duplicative WACBondCoupon class from the ABS ontology
Fixes: #1959 / SEC-191
> SEC-191 - Eliminate the class WACBondCoupon as redundant

- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- LOAN/LoansSpecific/CardAccounts.rdf
- LOAN/LoansSpecific/ConsumerLoans.rdf
Swapped the inheritance relation for consumer credit card agreement w.r.t unsecured consumer loan from being in the consumer loans ontology to the card accounts ontology and released consumer loans.
Fixes: #1961 / SEC-192
> SEC-192 - Move the inheritance link between consumer loan and credit cards to the credit cards ontology

- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- BE/GovernmentEntities/GovernmentEntities.rdf
- LOAN/LoansSpecific/ConsumerLoans.rdf
- LOAN/LoansSpecific/StudentLoans.rdf
Added two classes to the student loans ontology, made minor metadata changes in government entities, consumer loans
Fixes: #1963 / LOAN-167
> LOAN-167 - The student loan ontology is missing government-backed student loan

- FBC/DebtAndEquities/Debt.rdf
- SEC/Debt/AssetBackedSecurities.rdf
Added the concept of a lease, capital lease, and motor vehicle lease to the Debt ontology and added motor vehicle lease to auto debt pool
Fixes: #1965 / SEC-193
> SEC-193 - The concept of an auto loan pool in ABS requires the notion of a motor vehicle lease

- BE/GovernmentEntities/EuropeanJurisdiction/UKGovernmentEntitiesAndJurisdictions.rdf
fibo-be-ge-ukj:EnglandAndWalesJurisdiction declares fibo-fnd-law-jur:hasReach
lcc-3166-2-gb:EnglandAndWales, which I could not find. So in this branch I replaced it with two references to both England and Wales individually.
Fixes: #1950
> issue-1950: add separate references to england and wales

- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- FBC/DebtAndEquities/Debt.rdf
- SEC/Debt/PoolBackedSecurities.rdf
1. Augmented the CDS ontology to include credit default swap index and basket of credit default swaps as a starting point for adding attachement and detachment points and other analytics
2. Added concepts including collateral value as of date and 'has estimated total collateral value at issuance'
3. Added concepts related to attachment and detachment points
Fixes: #1973 / DER-138
> DER-138 - Need to add relationships to tranches and model them with respect to an index tranche CDS

- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
Moved the nominal representing auction method from CDS to instrument pricing (it's IRI was for the instrument pricing ontology already) and revised its metadata to simplify the definition and add an explanatory note
Fixes: #1977 / DER-140
> DER-140 - Wording of the definition of AuctionMethod in CDS is clumsy

- SEC/Securities/SecuritiesClassification.rdf
1. added the ICB benchmark and scheme managed by FTSE Russell to securities classification
2. added the GICS classifier (code) and scheme managed by S&P to securities classification
Fixes: #1981 / SEC-119
> SEC-119 - Need to bring in classification schemes that are used by the SEC and other regulators for classifying shares

- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- DER/DerivativesContracts/CommoditiesContracts.rdf
- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/Swaps.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FND/Accounting/CurrencyAmount.rdf
- LOAN/LoansGeneral/LoanApplications.rdf
- LOAN/LoansGeneral/Loans.rdf
1. In order to correct incongruent definitions, we first realigned the distinction between notional and nominal amount across all kinds of instruments
2. Added subproperties of hasNotionalAmount per the CFI standard in DerivativesBasics
3. Added commodity index to the commodities contracts ontology
Fixes: #1983 / DER-127
> DER-127 - Coverage of Commodity Swaps with respect to the CFI standard is incomplete

- DER/DerivativesContracts/CurrencyContracts.rdf
- DER/RateDerivatives/IRSwaps.rdf
1. Moved currency derivative up the class hierarchy a level so that it is a direct subclass of derivative instrument level so that it is a direct subclass of derivative instrument
2. Simplified / cleaned up the swaps hierarchy and added the definition of a fixed-fixed interest rate swap, which was a gap
Fixes: #1991 / DER-126
> DER-126 - Need to clean up the hierarchy of swap-related events

- DER/DerivativesContracts/Swaps.rdf
- DER/RateDerivatives/IRSwaps.rdf
- FBC/DebtAndEquities/Debt.rdf
- FBC/FinancialInstruments/Settlement.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- FND/DatesAndTimes/FinancialDates.rdf
- FND/DatesAndTimes/Occurrences.rdf
- FND/Utilities/Analytics.rdf
- LOAN/LoansGeneral/Loans.rdf
- SEC/Debt/Bonds.rdf
- SEC/Debt/DebtInstruments.rdf
- SEC/Equities/EquityInstruments.rdf
- SEC/Securities/ParametricSchedules.rdf
1. Replaced the term 'swap stream' with 'swap leg' or 'leg' in some cases
2. Moved general concepts related to anchor dates, calculations and calculation periods to financial dates, to enable broader use
3. Moved concepts related to interest rate schedules and calculations to the debt ontology to normalize the pattern used across FIBO
4. Moved concepts related to step schedules to the debt instruments ontology and normalized their usage
Fixes: #1996 / FBC-317
> FBC-317 - The concepts related to interest rate schedules, rate resets and related events needs to be cleaned up

- DER/SecurityBasedDerivatives/SecurityBasedDerivatives.rdf
Added a number of kinds of debt baskets to the securities-based derivatives ontology which were missing, such as a credit facility debt basket, non-guarantor debt basket, and so forth.
Fixes: #1999 / SEC-181
> SEC-181 - Augment the set of debt baskets with some additional refinements

- FND/DatesAndTimes/Occurrences.rdf
Added a restriction stating that an occurrence is classified by an occurrence kind, as requested by the Retail Domain Task force at OMG but also as needed for more sophisticated queries related to events in FIBO, such as those related to corporate actions, and cash flow analysis.
Fixes: #2001 / FND-382
> FND-382 - Add an isClassifiedBy restriction on Occurrence

- etc/testing/hygiene_parameterized/testHygiene_performance_multiple_different_individuals.sparql
Fix to hygiene test reporting
This fixes the reporter from the hygiene test testHygiene_performance_multiple_different_individuals.sparql
Fixes: #1988
> Fix to report from testHygiene_performance_multiple_different_individuals

- IND/InterestRates/MarketDataProviders.rdf
- SEC/Securities/SecuritiesIdentification.rdf
- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
Revised the definition of ticker symbol per the FIGI 1.2 revision task force at OMG, with some adjustments based on a more expansive definition, and updated the reference individuals related to Thomson Reuters to reflect its sale of the market data subsidiary (rebranded as Refinitiv) to the London Stock Exchange Group. Also added provenance for some securities identifiers where they were lacking.
Fixes: #2009 / SEC-196
> SEC-196 - Revise the definition of ticker-symbol to broaden its scope

- FND/Parties/Parties.rdf
corrected bug for incorrect prefix on hasRole
Fixes: #2015
> GitHub-2015 - corrected bug for incorrect prefix on hasRole

- FBC/FinancialInstruments/FinancialInstruments.rdf
- FND/Agreements/Contracts.rdf
Better integrated contract principal and counterparty with the overall contract pattern; augmented restrictions on issuer to say that they must issue a contract and revised the definition per notes.
Fixes: #2013 / FBC-284
> FBC-284 - The definition of Issuer should be adjusted to allow the same issuer to issue more than one

- FBC/FunctionalEntities/EuropeanEntities/EuropeanFinancialServicesEntitiesIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USExampleIndividuals.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USFinancialServicesEntitiesIndividuals.rdf
- IND/InterestRates/MarketDataProviders.rdf
This removes the fractional second part of xsd:dataTime values as required by the spec.
Fixes: #1993
> Fix to fractional seconds trailing zeros

- AboutFIBODev.rdf
- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd.rdf
- SEC/AllSEC-Europe.rdf
- SEC/AllSEC-ExampleIndividuals.rdf
- SEC/Equities/EquityInstruments.rdf
- SEC/Securities/EuropeanSecurities/EUSecuritiesRestrictions.rdf
- SEC/Securities/MetadataSECSecurities.rdf
- SEC/Securities/NorthAmericanSecurities/USSecuritiesRestrictions.rdf
- catalog-v001.xml
1. Added new EU securities restrictions ontology
2. Revised metadata files to add the ontology (load and metadata)
Fixes: #2030 / SEC-97
> SEC-97 - Regulatory related missing properties of exchange specific stock

- FBC/DebtAndEquities/Debt.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
- MD/DebtTemporal/DebtAnalytics.rdf
1. Added a definition for accrued interest to the debt ontology and removed it from debt analytics
2. Moved clean price, dirty price, derived price and related property to the pricing ontology
Fixes: #2033 / SEC-185
> SEC-185 - Several terms in the DebtAnalytics ontology should be included in the InstrumentPricing ontology

- DER/DerivativesContracts/CurrencyContracts.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- IND/ForeignExchange/ForeignExchange.rdf
1. Moved the notion of buying and selling currencies to financial instruments to make the properties available to all currency instruments
2. Added the notion of a source for any quoted exchange rate and updated the definition of currency derivative to include the ability to specify the source used to determine the rate that the contract is based on
Fixes: #2035 / DER-143
> DER-143 - There is a gap with respect to the currency contracts related to the notion of an exchange rate

- FBC/FunctionalEntities/NorthAmericanEntities/USNationalInformationCenterControlledVocabularies.rdf
address misclassification of the scheme for the NIC repository and related axioms (was a class, is now a named individual)
Fixes: #2041
> GitHub-2041 - fibo-fbc-fct-usnic:NationalInformationCenterClassificationSchemeAndCodeSet is used as an object of owl:hasValue

- SEC/Securities/SecuritiesIdentificationIndividuals.rdf
addressed punning issue with the EuroClear / Clearstream Common Code
Fixes: #2040
> GitHub-2040 - fibo-sec-sec-idind:EuroclearClearstreamCommonCode is used as an object of owl:hasValue

- IND/EconomicIndicators/EconomicIndicators.rdf
- IND/MarketIndices/BasketIndices.rdf
Eliminated the use of hasArgument to refer to certain inputs to various expressions which caused punning, added two properties and refined restrictions to eliminate the obsolete restrictions in the same ontology (GitHub-2028), and normalized language in definitions to eliminate indefinite articles, in compliance with ISO 704
Fixes: #2038
> GitHub-2038 - Implicit punning of OWL Classes in triples (as subjects) with datatype property

- CAE/CorporateEvents/ISO15022-CorporateActionIndividuals.rdf
- IND/MarketIndices/EquityIndexExampleIndividuals.rdf
Revised the modeling strategy for ISO 15022/20022 corporate actions and example market indices baskets to eliminate punning issues
Fixes: #2039
> GitHub-2039 - Implicit punning of OWL Classes in triples (as objects) with object property

- BE/GovernmentEntities/EuropeanJurisdiction/NorthernEuropeGovernmentEntitiesAndJurisdictions.rdf
Corrected the range of hasReach for the jurisdiction of Norway
Fixes: #2037
> GitHub-2037 - Wrong value of fibo-fnd-law-jur:hasReach in fibo-be-ge-neuj:JurisdictionOfNorway

- DER/DerivativesContracts/DerivativesBasics.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
1. eliminated a redundant restriction on product lifecycle stage
2. eliminated a redundant restriction on derivative instrument
Fixes: #2028
> GitHub-2028 - Eliminate / address obsolete restrictions identified through hygiene testing

- SEC/Securities/NorthAmericanSecurities/USSecuritiesRestrictions.rdf
Eliminated double spaces in annotations in the US securities restrictions ontology, which occurred in the original text copied to add background details.
Fixes: #2054
> GitHub-2054 - Eliminate extra space in annotations on the US Securities Restrictions ontology

- FBC/DebtAndEquities/Debt.rdf
- FND/AgentsAndPeople/People.rdf
- FND/Agreements/Contracts.rdf
- FND/Arrangements/Documents.rdf
- FND/Arrangements/Ratings.rdf
- FND/Arrangements/Reporting.rdf
- SEC/Debt/Bonds.rdf
- SEC/Securities/SecuritiesIssuance.rdf
1. Added a synonym of 'has dated date' to 'has initial interest accrual date'. 'has initial interest accrual date' is a property of interest payment terms, which is a subclass of debt terms – all credit agreements have some debt terms in FIBO, so the question is whether we need a property chain from the instrument to the concepts that define interest payment terms ... otherwise this should be sufficient.
2. Added an optional restriction with date of issuance to contract, as other kinds of contracts, such as insurance policies, can have a different date of issuance from the execution and effective dates.
3. Replaced instances of 'has date of issuance' from FND documents with the Commons equivalent (missed in the initial updates for Commons 1.1)
4. Added a restriction for hasSeries on bond …
> FBC-322 - Missing synonyms on certain properties of financial instruments

- AboutFIBODev.rdf
- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- BP/SecuritiesIssuance/AgencyMBSIssuance.rdf
- BP/SecuritiesIssuance/PrivateLabelMBSIssuance.rdf
- FBC/DebtAndEquities/Debt.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FND/Agreements/Contracts.rdf
- FND/AllFND.rdf
- FND/Places/Addresses.rdf
- FND/Places/Locations.rdf
- FND/Places/MetadataFNDPlaces.rdf
- FND/Places/RealProperty.rdf
- FND/ProductsAndServices/ProductsAndServices.rdf
- LOAN/AllLOAN.rdf
- LOAN/LoansGeneral/Loans.rdf
- LOAN/LoansSpecific/LoanProducts.rdf
- LOAN/RealEstateLoans/ConstructionLoans.rdf
- LOAN/RealEstateLoans/HomeMortgageDisclosureActCoveredMortgages.rdf
- LOAN/RealEstateLoans/MetadataLOANRealEstateLoans.rdf
- LOAN/RealEstateLoans/MortgageOrigination.rdf
- LOAN/RealEstateLoans/Mortgages.rdf
- SEC/Debt/CollateralizedDebtObligations.rdf
- SEC/Debt/DebtInstruments.rdf
- SEC/Debt/MortgageBackedSecurities.rdf
- catalog-v001.xml
1. Split the MortgageLoans ontology into two separate ontologies - one small-ish ontology describing mortgages, but limited to primary contract details, with a second ontology including the origination and servicing content that was previously in MortgageLoans. Resulting ontologies include Mortages and MortgageOrigination (which may be split again into origination and servicing components)
2. Move real property concepts to a separate ontology in Foundations and revise definitions to reflect what is in the law
3. Refined the definition of collateralized loan, including higher level concepts in the debt and contracts ontologies based on SME input
4. Revised the definition mortgage to distinguish between the notion of something secured by real property and the contract, leveraging regulatory …
> LOAN-168 - Revise the Loans ontologies as the basis for green loans

- AboutFIBODev.rdf
- AboutFIBOProd-IncludingReferenceData.rdf
- AboutFIBOProd-TBoxOnly.rdf
- AboutFIBOProd.rdf
- FND/Utilities/Analytics.rdf
- LOAN/AllLOAN.rdf
- LOAN/LoansSpecific/GreenLoans.rdf
- SEC/AllSEC-Europe.rdf
- SEC/AllSEC-ExampleIndividuals.rdf
- SEC/AllSEC-NorthAmerica.rdf
- SEC/AllSEC-ReferenceIndividuals.rdf
- SEC/AllSEC.rdf
- SEC/Debt/DistributedLoans.rdf
- SEC/Debt/MetadataSECDebt.rdf
- SEC/Equities/DepositaryReceipts.rdf
- SEC/MetadataSEC.rdf
- catalog-v001.xml
1. Revised the definition of loan participation note per discussion in the DER FCT
2. Renamed SyndicatedLoans to DistributedLoans per discussion in the SEC FCT telecon and released it, including all related metadata
3. Added the concept of a key performance indicator to the analytics ontology in FND
4. Added concepts related to sustainability-linked loans to the green loans ontology
5. Refined definitions of KPI and sustainability performance target to link the two as series of dated values (observations as well as targets)
Fixes: #2072 / LOAN-169a
> LOAN-169a - Add Sustainability-linked loan and related concepts

- FND/GoalsAndObjectives/Objectives.rdf
- LOAN/LoansSpecific/GreenLoans.rdf
1. Added the general concept of a project to the objectives ontology
2. Add the concept of a green project and link it to the green project use of proceeds concept
3. Add definitions for transition loans, strategies and projects
4. Add the notion of target and observed values as part of SPTs and to support KPI calculations
Fixes: #2074 / LOAN-169
> LOAN-169b - Add concepts related to transition loans, including supporting green projects

- FND/GoalsAndObjectives/Objectives.rdf
- LOAN/LoansSpecific/GreenLoans.rdf
This includes adding a number of identifiers - for programs, projects, KPIs, and SPTs, as well as assessment boundaries to support more sophisticated project tracking requirements.
Fixes: #2076 / LOAN-169c
> LOAN-169c - Extend environmental and sustainability related concepts to better reflect reporting and tracking requirements

- LOAN/LoansSpecific/GreenLoans.rdf
Addressed overly constraining restriction per feedback
Fixes: #2078
> Loosened constraints on isEvidencedBy per stakeholder feedback

- ACTUS/ACTUSControlledVocabulary.rdf
- ACTUS/MetadataACTUS.rdf
- AboutFIBODev.rdf
- FBC/DebtAndEquities/Debt.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- MetadataFIBO.rdf
- catalog-v001.xml
This initial pull request creates a new top-level domain in FIBO for the ACTUS algorithmic contract types taxonomy and related controlled vocabulary terms.
Fixes: #2080 / FND-388
> FND-388 - Create a new domain area to cover the mapping between FIBO and the ACTUS standard

- etc/vocabulary/scaffolding.ttl
fix scaffolding.ttl with terminating dot after last @prefix
Fixes: #2092
> Note: I have not spent much time looking at the overall project, but this change appears reasonably small and tested the file `scaffolding.ttl` in my private project with python rdflib. Please let me know if I must understand the overall project and only then complete the checklist before re-submitting the patch.
> fix scaffolding.ttl with terminating dot after last @prefix

- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
- DER/DerivativesContracts/Options.rdf
1. added OTC derivative instrument, UPI and UPI service provider to derivative basics
2. added OTC derivative instrument as a parent of exotic option and forward (vs. OTC instrument)
Fixes: #2094 / DER-146
> DER-146 - Add a definition for the ISO 4914 Unique Product Identifier for OTC instruments

- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- SEC/Equities/EquityInstruments.rdf
Augmented the definition of shareholding with the number of shares and a reference to the share in question; revised the definition of equity position to leverage shareholding
Fixes: #2107 / BE-254
> BE-254 - The definition of shareholding is missing details

- FBC/DebtAndEquities/Debt.rdf
- LOAN/LoansGeneral/Loans.rdf
- LOAN/RealEstateLoans/Mortgages.rdf
Moved 'has credit limit' to the Debt ontology and added two other properties needed to describe revolving lines of credit
Fixes: #2105 / FBC-324
> FBC-324 - The property 'has credit limit' is defined in loans and should be available for any credit facility in FBC

- DER/DerivativesContracts/CommoditiesContracts.rdf
- DER/DerivativesContracts/CurrencyContracts.rdf
- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/ExoticOptions.rdf
- DER/DerivativesContracts/FuturesAndForwards.rdf
- DER/DerivativesContracts/Options.rdf
- DER/DerivativesContracts/RightsAndWarrants.rdf
- DER/DerivativesContracts/Swaps.rdf
- DER/RateDerivatives/IRSwaps.rdf
- DER/RateDerivatives/RateDerivatives.rdf
- DER/SecurityBasedDerivatives/EquitySwaps.rdf
- DER/SecurityBasedDerivatives/SecurityBasedDerivatives.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FND/Arrangements/Assessments.rdf
- SEC/Debt/AssetBackedSecurities.rdf
1. modify the role of underlier to be a subclass of undergoer; rename commodity underlying asset to commodity derivative underlier to clarify the intent
2. eliminate concepts including various 'observables' used as underliers for securities derivatives (note that this step highlights some of the reasoning issues around the inconsistencies in representation of certain kinds of instruments and the use of the hasUnderlier property)
3. normalize the representation of underliers, including use of the property hasUnderlier in restrictions, across various derivatives
4. revised the asset-backed securities ontology to use 'is based on' vs. 'has underlier' to limit the possibility of confusion due to a more general use of the term 'underlier'
Fixes: #2103 / DER-112
> DER-112 - There are mixed approaches to representing underliers - some use hasUnderlier (formerly hasIdentity) and others do not

- DER/DerivativesContracts/DerivativesBasics.rdf
- DER/DerivativesContracts/Options.rdf
- DER/RateDerivatives/IRSwaps.rdf
- DER/RateDerivatives/RateDerivatives.rdf
- FBC/FunctionalEntities/RegulatoryAgencies.rdf
- SEC/Debt/PoolBackedSecurities.rdf
Moved several classes from the rate derivatives class to derivatives basics for better integration and interoperability, added provenance and detail to a couple of the definitions and address issues uncovered in restrictions as part of testing
Fixes: #2119 / DER-90
> DER-90 - Clean-up definitions in the rate derivatives ontology

- DER/DerivativesContracts/DerivativesMasterAgreements.rdf
- FBC/DebtAndEquities/CreditEvents.rdf
- FBC/DebtAndEquities/Debt.rdf
- FND/Agreements/Contracts.rdf
- FND/Law/LegalCapacity.rdf
- FND/ProductsAndServices/PaymentsAndSchedules.rdf
Clean-up of the master agreements ontology as follows:
1. Eliminate the concept of a credit event definition, which is now covered in FBC
2. Extended the definition of credit support agreement and better integrated that with other concepts in FIBO
3. Refined and combined concepts related to termination and early termination
4. Eliminated the concepts of a master-agreement specific contractual commitment, element, and representation, which were defined as catch-alls and duplicative of detail in contracts
5. Further integration of content related to credit events, where what was already in FIBO is more comprehensive and should be leveraged (and some may apply to the master agreement rather than the credit support agreement, or both)
6. Refined the definition of a credit support beneficiary, …
> DER-55 - Potential issues with the DerivativesMasterAgreements ontology

- BE/GovernmentEntities/GovernmentEntities.rdf
- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- DER/DerivativesContracts/CommoditiesContracts.rdf
- DER/SecurityBasedDerivatives/SecurityBasedDerivatives.rdf
- FBC/DebtAndEquities/Debt.rdf
- FBC/FinancialInstruments/FinancialInstruments.rdf
- FBC/FinancialInstruments/InstrumentPricing.rdf
- FBC/ProductsAndServices/FinancialProductsAndServices.rdf
- FND/Accounting/CashFlows.rdf
- FND/Accounting/CurrencyAmount.rdf
- FND/DatesAndTimes/FinancialDates.rdf
- FND/ProductsAndServices/PaymentsAndSchedules.rdf
- IND/EconomicIndicators/EconomicIndicators.rdf
- IND/ForeignExchange/ForeignExchange.rdf
- IND/Indicators/Indicators.rdf
- IND/MarketIndices/BasketIndices.rdf
- LOAN/LoansSpecific/LoanProducts.rdf
- SEC/Debt/CollateralizedDebtObligations.rdf
- SEC/Debt/MortgageBackedSecurities.rdf
- SEC/Funds/CollectiveInvestmentVehicles.rdf
- SEC/Securities/Baskets.rdf
Revised a number of ontologies across FIBO to replace hasConstituent with hasMember for better semantic consistency based on updated definitions in OMG Commons
Fixes: #2142 / FND-396
> FND-396 - 43 incorrect uses of hasConstituent across FIBO

- DER/DerivativesContracts/RightsAndWarrants.rdf
- SEC/Debt/Bonds.rdf
Revised the definition and parent class of 'bond with warrant' to use the CFI definition, and added a restriction in the rights and warrants ontology to connect the bond to at least one warrant
Fixes: #2144 / SEC-207
> SEC-207 - Bond with warrant is defined as an offering without links to the bond or related warrant

- DER/DerivativesContracts/DerivativesBasics.rdf
Added missing restrictions needed for equity warrants to derivative instrument, as they apply much more broadly
Fixes: #2150 / DER-151
> DER-151 - No property to represent the number of shares in an EquityWarrant

- BE/LegalEntities/LegalPersons.rdf
- DER/CreditDerivatives/CreditDefaultSwaps.rdf
- FND/Arrangements/Documents.rdf
- FND/GoalsAndObjectives/Objectives.rdf
- MD/CIVTemporal/FundsTemporal.rdf
- SEC/Debt/CollateralizedDebtObligations.rdf
- SEC/Funds/CollectiveInvestmentVehicles.rdf
- SEC/Securities/SecurityAssets.rdf
1. Cleaned up redundant definitions related to special purpose vehicles, corrected a typo in a label in the CDS ontology, revised the definition of hasTerminationDate to allow for scheduled terminations, added a property for intended liquidation date to legal persons and a restriction using that property on SPV.
2. Augmented the Goals and Objectives ontology with the concept of a method and clarified some of the property definitions in that ontology
3. Moved performance related terminology to FundsTemporal in MD
4. Eliminated redundancies between the concept of a portfolio and the concept of a portfolio holding and merged the terms based on their restrictions and usage across FIBO
Fixes: #2160 / SEC-200
> SEC-200 - Clean-up the CIV ontology in SEC/Funds in order to leverage it for use in describing various kinds of more complex instruments, such as CDOs

- BE/GovernmentEntities/GovernmentEntities.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/CARegulatoryAgencies.rdf
- FBC/FunctionalEntities/NorthAmericanEntities/USRegulatoryAgencies.rdf
- FBC/FunctionalEntities/RegulatoryAgencies.rdf
- IND/EconomicIndicators/NorthAmericanIndicators/USEconomicIndicators.rdf
Several ontologies, primarily in FBC, were updated to use the Commons version of hasJurisdiction, and deprecate the older property in FIBO
Fixes: #2171 / FBC-338
> FBC-338 - Not all FIBO ontologies were updated to use the new Commons definition of hasJurisdiction, which should be corrected
